### ISSUE TITLE
[Plan] The loading skeleton for the entire page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1072]
列出需要加上 skeleton 的頁面

- [ ] #1179
- [ ] #1180
- [ ] #1181
- [ ] #1182
- [ ] #1183

ref: [design spec](https://www.figma.com/design/jgDW7ljfQ0RGvnebW9ve0h/iSunFA-Design-System?node-id=164-38170&m=dev)｜

**Comment by arealclimber** [comment]
## 規劃: 15 pt
- [ ] [dashboard page (The loading skeleton for the entire page) #1179](https://github.com/CAFECA-IO/iSunFA/issues/1179)  - 3 pt
- [ ] [project page (The loading skeleton for the entire page) #1180](https://github.com/CAFECA-IO/iSunFA/issues/1180)  - 3 pt
- [ ] [account page (The loading skeleton for the entire page) #1181](https://github.com/CAFECA-IO/iSunFA/issues/1181)  - 3 pt
- [ ] [salary page (The loading skeleton for the entire page) #1182](https://github.com/CAFECA-IO/iSunFA/issues/1182)  - 3 pt
- [ ] [report page (The loading skeleton for the entire page) #1183](https://github.com/CAFECA-IO/iSunFA/issues/1183)  - 3 pt

**Comment by arealclimber** [comment]
took 0.5 hrs
done
