### ISSUE TITLE
規劃 iSunFA 開發時程跟開票 setting

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#119]
- [ ] 根據 mockup 跟 [component diagram](https://github.com/CAFECA-IO/Documents/blob/main/ISF/ISF_Component_Diagram.md) 規劃 setting & subscription 桌面版跟行動版開發
- [ ] #1102
- [ ] #1103
- [ ] #1104
- [ ] #1105
- [ ] #1106
- [ ] #1107
- [ ] #1108
- [ ] #1109
- [ ] #1110
- [ ] #1111
- [ ] #1112
- [ ] #1113
- [ ] #1114
- [ ] #1115
- [ ] #1116
- [ ] #1117
- [ ] #1118
- [ ] #1119
- [ ] #1120
- [ ] #1121
- [ ] #1122
- [ ] #1123
- [ ] #1124
- [ ] #1125
- [ ] #1126
- [ ] #1127
- [ ] #1128
- [ ] #1129
- [ ] #1130
- [ ] #1131
- [ ] #1132
- [ ] #1133
- [ ] #1134
- [ ] #1135
- [ ] #1136
- [ ] #1137
- [ ] #1138
- [ ] #1139
- [ ] #1140
- [ ] #1141
- [ ] #1142
- [ ] #1143
- [ ] #1144
- [ ] #1145
- [ ] #1146
- [ ] #1147
- [ ] #1148
- [ ] #1149
- [ ] #1150
- [ ] #1151
- [ ] #1152
- [ ] #1153
- [ ] #1154
- [ ] #1155
- [ ] #1156
- [ ] #1157
-----
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/5bb22744-fb8a-44f5-9225-1d1262d70251)
![image](https://github.com/CAFECA-IO/iSunFA/assets/20677913/3bcc0760-e723-400a-a105-a6766f13dcfd)

ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1896-93471&m=dev)（[mobile](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=2744-198525&m=dev)）

**Comment by arealclimber** [comment]
- [ ] SettingPersonalPage (ISFMK00062) (desktop)
- [ ] SettingCompanyInfoPage (ISFMK00069) (desktop)
- [ ] SettingAccountTitlePage (ISFMK00031) (ISFMK00040) (desktop)
- [ ] TeamSettingsModal (desktop)
- [ ] AddAccountTitleModal (desktop)
- [ ] AccountTitle (desktop)
- [ ] AccountTitleList (desktop)
- [ ] SettingSideBar (desktop)
- [ ] FavoriteAccountTitle (desktop)
- [ ] MyNewAccountTitle (desktop)
- [ ] EditAccountTitleModal (desktop)
- [ ] AddAccountTitleModal (desktop)
- [ ] SettingClientListPage (ISFMK00032) (desktop)
- [ ] AddTransactionPartnerModal (desktop)
- [ ] EditTransactionPartnerModal (desktop)
- [ ] FavoriteClient (desktop)
- [ ] ClientList (desktop)
- [ ] SettingAdministratorPage (ISFMK00005) (desktop)
- [ ] AdministratorList (desktop)
- [ ] AddAdministratorModal (desktop)
- [ ] AdministratorDetailPage (ISFMK00063) (desktop)
- [ ] SubscriptionAndBillsPage (ISFMK00053)(ISFMK00036) (ISFMK00020) (desktop)
- [ ] MyCards (desktop)
- [ ] Subscription (desktop)
- [ ] AddNewCardsModal (desktop)
- [ ] SubscriptionModal (desktop)
- [ ] Bills (desktop)
- [ ] ChangeSubscriptionModal (desktop)
- [ ] SettingPersonalPage (ISFMK00062)  (mobile)
- [ ] SettingCompanyInfoPage (ISFMK00069)  (mobile)
- [ ] SettingAccountTitlePage (ISFMK00031) (ISFMK00040)  (mobile)
- [ ] TeamSettingsModal  (mobile)
- [ ] AddAccountTitleModal  (mobile)
- [ ] AccountTitle  (mobile)
- [ ] AccountTitleList  (mobile)
- [ ] SettingSideBar  (mobile)
- [ ] FavoriteAccountTitle  (mobile)
- [ ] MyNewAccountTitle  (mobile)
- [ ] EditAccountTitleModal  (mobile)
- [ ] AddAccountTitleModal  (mobile)
- [ ] SettingClientListPage (ISFMK00032)  (mobile)
- [ ] AddTransactionPartnerModal  (mobile)
- [ ] EditTransactionPartnerModal  (mobile)
- [ ] FavoriteClient  (mobile)
- [ ] ClientList  (mobile)
- [ ] SettingAdministratorPage (ISFMK00005)  (mobile)
- [ ] AdministratorList  (mobile)
- [ ] AddAdministratorModal  (mobile)
- [ ] AdministratorDetailPage (ISFMK00063)  (mobile)
- [ ] SubscriptionAndBillsPage (ISFMK00053)(ISFMK00036) (ISFMK00020)  (mobile)
- [ ] MyCards  (mobile)
- [ ] Subscription  (mobile)
- [ ] AddNewCardsModal  (mobile)
- [ ] SubscriptionModal  (mobile)
- [ ] Bills  (mobile)
- [ ] ChangeSubscriptionModal  (mobile)

**Comment by arealclimber** [comment]
took 1.5 hrs
remaining 6 hrs

**Comment by arealclimber** [comment]
took 1.5 hr
remaining 4 hrs
-----
## Setting (`#1102~#1126`) 115 pt
- [ ] [SettingPersonalPage (ISFMK00062) (desktop) #1102](https://github.com/CAFECA-IO/iSunFA/issues/1102)  - 8 pt
- [ ] [SettingCompanyInfoPage (ISFMK00069) (desktop) #1103](https://github.com/CAFECA-IO/iSunFA/issues/1103)  - 8 pt
- [ ] [SettingAccountTitlePage (ISFMK00031) (ISFMK00040) (desktop) #1104](https://github.com/CAFECA-IO/iSunFA/issues/1104)  - 8 pt
- [ ] [TeamSettingsModal (desktop) #1105](https://github.com/CAFECA-IO/iSunFA/issues/1105)  - 3 pt
- [ ] [AddAccountTitleModal (desktop) #1106](https://github.com/CAFECA-IO/iSunFA/issues/1106)  - 3 pt
- [ ] [AccountTitle (desktop) #1107](https://github.com/CAFECA-IO/iSunFA/issues/1107)  - 2 pt
- [ ] [AccountTitleList (desktop) #1108](https://github.com/CAFECA-IO/iSunFA/issues/1108)  - 5 pt
- [ ] [SettingSideBar (desktop) #1109](https://github.com/CAFECA-IO/iSunFA/issues/1109)  - 3 pt
- [ ] [FavoriteAccountTitle (desktop) #1110](https://github.com/CAFECA-IO/iSunFA/issues/1110)  - 2 pt
- [ ] [MyNewAccountTitle (desktop) #1111](https://github.com/CAFECA-IO/iSunFA/issues/1111)  - 2 pt
- [ ] [EditAccountTitleModal (desktop) #1112](https://github.com/CAFECA-IO/iSunFA/issues/1112)  - 3 pt
- [ ] [AddAccountTitleModal (desktop) #1113](https://github.com/CAFECA-IO/iSunFA/issues/1113)  - 3 pt
- [ ] [SettingClientListPage (ISFMK00032) (desktop) #1114](https://github.com/CAFECA-IO/iSunFA/issues/1114)  - 8 pt
- [ ] [AddTransactionPartnerModal (desktop) #1115](https://github.com/CAFECA-IO/iSunFA/issues/1115)  - 3 pt
- [ ] [EditTransactionPartnerModal (desktop) #1116](https://github.com/CAFECA-IO/iSunFA/issues/1116)  - 3 pt
- [ ] [FavoriteClient (desktop) #1117](https://github.com/CAFECA-IO/iSunFA/issues/1117)  - 5 pt
- [ ] [ClientList (desktop) #1118](https://github.com/CAFECA-IO/iSunFA/issues/1118)  - 5 pt
- [ ] [SettingAdministratorPage (ISFMK00005) (desktop) #1119](https://github.com/CAFECA-IO/iSunFA/issues/1119)  - 8 pt
- [ ] [AdministratorList (desktop) #1120](https://github.com/CAFECA-IO/iSunFA/issues/1120)  - 5 pt
- [ ] [AddAdministratorModal (desktop) #1121](https://github.com/CAFECA-IO/iSunFA/issues/1121)  - 3 pt
- [ ] [AdministratorDetailPage (ISFMK00063) (desktop) #1122](https://github.com/CAFECA-IO/iSunFA/issues/1122)  - 8 pt
- [ ] [SubscriptionAndBillsPage (ISFMK00053)(ISFMK00036) (ISFMK00020) (desktop) #1123](https://github.com/CAFECA-IO/iSunFA/issues/1123)  - 8 pt
- [ ] [MyCards (desktop) #1124](https://github.com/CAFECA-IO/iSunFA/issues/1124)  - 3 pt
- [ ] [Subscription (desktop) #1125](https://github.com/CAFECA-IO/iSunFA/issues/1125)  - 3 pt
- [ ] [AddNewCardsModal (desktop) #1126](https://github.com/CAFECA-IO/iSunFA/issues/1126)  - 3 pt

**Comment by arealclimber** [comment]
# Setting (#1102~#1157) 規劃: 201 pt
- [ ] [SettingPersonalPage (ISFMK00062) (desktop) #1102](https://github.com/CAFECA-IO/iSunFA/issues/1102)  - 8 pt
- [ ] [SettingCompanyInfoPage (ISFMK00069) (desktop) #1103](https://github.com/CAFECA-IO/iSunFA/issues/1103)  - 8 pt
- [ ] [SettingAccountTitlePage (ISFMK00031) (ISFMK00040) (desktop) #1104](https://github.com/CAFECA-IO/iSunFA/issues/1104)  - 8 pt
- [ ] [CompanySettingsModal (TeamSettingsModal on component diagram) (desktop) #1105](https://github.com/CAFECA-IO/iSunFA/issues/1105)  - 3 pt
- [ ] [AddAccountTitleModal (desktop) #1106](https://github.com/CAFECA-IO/iSunFA/issues/1106)  - 3 pt
- [ ] [AccountTitle (desktop) #1107](https://github.com/CAFECA-IO/iSunFA/issues/1107)  - 2 pt
- [ ] [AccountTitleList (desktop) #1108](https://github.com/CAFECA-IO/iSunFA/issues/1108)  - 5 pt
- [ ] [SettingSideBar (desktop) #1109](https://github.com/CAFECA-IO/iSunFA/issues/1109)  - 3 pt
- [ ] [FavoriteAccountTitle (desktop) #1110](https://github.com/CAFECA-IO/iSunFA/issues/1110)  - 2 pt
- [ ] [MyNewAccountTitle (desktop) #1111](https://github.com/CAFECA-IO/iSunFA/issues/1111)  - 2 pt
- [ ] [EditAccountTitleModal (desktop) #1112](https://github.com/CAFECA-IO/iSunFA/issues/1112)  - 3 pt
- [ ] [AddAccountTitleModal (desktop) #1113](https://github.com/CAFECA-IO/iSunFA/issues/1113)  - 3 pt
- [ ] [SettingClientListPage (ISFMK00032) (desktop) #1114](https://github.com/CAFECA-IO/iSunFA/issues/1114)  - 8 pt
- [ ] [AddTransactionPartnerModal (desktop) #1115](https://github.com/CAFECA-IO/iSunFA/issues/1115)  - 3 pt
- [ ] [EditTransactionPartnerModal (desktop) #1116](https://github.com/CAFECA-IO/iSunFA/issues/1116)  - 3 pt
- [ ] [FavoriteClient (desktop) #1117](https://github.com/CAFECA-IO/iSunFA/issues/1117)  - 5 pt
- [ ] [ClientList (desktop) #1118](https://github.com/CAFECA-IO/iSunFA/issues/1118)  - 5 pt
- [ ] [SettingAdministratorPage (ISFMK00005) (desktop) #1119](https://github.com/CAFECA-IO/iSunFA/issues/1119)  - 8 pt
- [ ] [AdministratorList (desktop) #1120](https://github.com/CAFECA-IO/iSunFA/issues/1120)  - 5 pt
- [ ] [AddAdministratorModal (desktop) #1121](https://github.com/CAFECA-IO/iSunFA/issues/1121)  - 5 pt
- [ ] [AdministratorDetailPage (ISFMK00063) (desktop) #1122](https://github.com/CAFECA-IO/iSunFA/issues/1122)  - 8 pt
- [ ] [SubscriptionAndBillsPage (ISFMK00053)(ISFMK00036) (ISFMK00020) (desktop) #1123](https://github.com/CAFECA-IO/iSunFA/issues/1123)  - 8 pt
- [ ] [MyCards (desktop) #1124](https://github.com/CAFECA-IO/iSunFA/issues/1124)  - 3 pt
- [ ] [Subscription (desktop) #1125](https://github.com/CAFECA-IO/iSunFA/issues/1125)  - 3 pt
- [ ] [AddNewCardsModal (desktop) #1126](https://github.com/CAFECA-IO/iSunFA/issues/1126)  - 3 pt
- [ ] [SubscriptionModal (desktop) #1127](https://github.com/CAFECA-IO/iSunFA/issues/1127)  - 5 pt
- [ ] [Bills (desktop) #1128](https://github.com/CAFECA-IO/iSunFA/issues/1128)  - 3 pt
- [ ] [ChangeSubscriptionModal (desktop) #1129](https://github.com/CAFECA-IO/iSunFA/issues/1129)  - 3 pt
- [ ] [SettingPersonalPage (ISFMK00062)  (mobile) #1130](https://github.com/CAFECA-IO/iSunFA/issues/1130)  - 8 pt
- [ ] [SettingCompanyInfoPage (ISFMK00069)  (mobile) #1131](https://github.com/CAFECA-IO/iSunFA/issues/1131)  - 8 pt
- [ ] [SettingAccountTitlePage (ISFMK00031) (ISFMK00040)  (mobile) #1132](https://github.com/CAFECA-IO/iSunFA/issues/1132)  - 8 pt
- [ ] [CompanySettingsModal (TeamSettingsModal on component diagram) (mobile) #1133](https://github.com/CAFECA-IO/iSunFA/issues/1133)  - 1 pt
- [ ] [AddAccountTitleModal  (mobile) #1134](https://github.com/CAFECA-IO/iSunFA/issues/1134)  - 1 pt
- [ ] [AccountTitle  (mobile) #1135](https://github.com/CAFECA-IO/iSunFA/issues/1135)  - 2 pt
- [ ] [AccountTitleList  (mobile) #1136](https://github.com/CAFECA-IO/iSunFA/issues/1136)  - 2 pt
- [ ] [SettingSideBar  (mobile) #1137](https://github.com/CAFECA-IO/iSunFA/issues/1137)  - 2 pt
- [ ] [FavoriteAccountTitle  (mobile) #1138](https://github.com/CAFECA-IO/iSunFA/issues/1138)  - 2 pt
- [ ] [MyNewAccountTitle  (mobile) #1139](https://github.com/CAFECA-IO/iSunFA/issues/1139)  - 2 pt
- [ ] [EditAccountTitleModal  (mobile) #1140](https://github.com/CAFECA-IO/iSunFA/issues/1140)  - 1 pt
- [ ] [AddAccountTitleModal  (mobile) #1141](https://github.com/CAFECA-IO/iSunFA/issues/1141)  - 1 pt
- [ ] [SettingClientListPage (ISFMK00032)  (mobile) #1142](https://github.com/CAFECA-IO/iSunFA/issues/1142)  - 2 pt
- [ ] [AddTransactionPartnerModal  (mobile) #1143](https://github.com/CAFECA-IO/iSunFA/issues/1143)  - 1 pt
- [ ] [EditTransactionPartnerModal  (mobile) #1144](https://github.com/CAFECA-IO/iSunFA/issues/1144)  - 1 pt
- [ ] [FavoriteClient  (mobile) #1145](https://github.com/CAFECA-IO/iSunFA/issues/1145)  - 3 pt
- [ ] [ClientList  (mobile) #1146](https://github.com/CAFECA-IO/iSunFA/issues/1146)  - 3 pt
- [ ] [SettingAdministratorPage (ISFMK00005)  (mobile) #1147](https://github.com/CAFECA-IO/iSunFA/issues/1147)  - 8 pt
- [ ] [AdministratorList  (mobile) #1148](https://github.com/CAFECA-IO/iSunFA/issues/1148)  - 3 pt
- [ ] [AddAdministratorModal  (mobile) #1149](https://github.com/CAFECA-IO/iSunFA/issues/1149)  - 1 pt
- [ ] [AdministratorDetailPage (ISFMK00063)  (mobile) #1150](https://github.com/CAFECA-IO/iSunFA/issues/1150)  - 2 pt
- [ ] [SubscriptionAndBillsPage (ISFMK00053)(ISFMK00036) (ISFMK00020)  (mobile) #1151](https://github.com/CAFECA-IO/iSunFA/issues/1151)  - 2 pt
- [ ] [MyCards  (mobile) #1152](https://github.com/CAFECA-IO/iSunFA/issues/1152)  - 2 pt
- [ ] [Subscription  (mobile) #1153](https://github.com/CAFECA-IO/iSunFA/issues/1153)  - 2 pt
- [ ] [AddNewCardsModal  (mobile) #1154](https://github.com/CAFECA-IO/iSunFA/issues/1154)  - 1 pt
- [ ] [SubscriptionModal  (mobile) #1155](https://github.com/CAFECA-IO/iSunFA/issues/1155)  - 1 pt
- [ ] [Bills  (mobile) #1156](https://github.com/CAFECA-IO/iSunFA/issues/1156)  - 2 pt
- [ ] [ChangeSubscriptionModal  (mobile) #1157](https://github.com/CAFECA-IO/iSunFA/issues/1157)  - 1 pt

**Comment by arealclimber** [comment]
took 3.5 hrs
done
