### ISSUE TITLE
[FEATURE] - 修改使用 fido2 實作登入的方法以獲得 challenge

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#1417]
### Summary

修改 useAPI 方法以使用 async/await 獲取 fido2 登入 challenge。

### Tasks

- [x] 分析現有的 useAPI 方法，確定需要修改的部分
- [x] 修改方法以適應 fido2 獲取 challenge 的需求
- [x] 使用 async/await 處理非同步操作
- [x] 新增測試用的 challenge API
- [x] 測試改寫的方法

### Dependencies

API Availability

**Comment by TzuHanLiang** [comment]
took 5hrs
done
