### ISSUE TITLE
[Plan] list missing API and layout issues of setting page and employee page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1557]
### Setting page - company

- [ ]  `GET company` API integration on employee page
- [ ]  `POST delete company` API integration on employee page
- [ ]  `POST transfer ownership` API integration on employee page
- [ ]  `POST rename company` API integration on employee page
- [ ] Team setting modal (desktop & mobile)
- [ ] Layout of procedure of deleting company (estimated according to hypothesis)
- [ ] Layout of procedure of transferring ownership (estimated according to hypothesis)

### Setting page - accounting title

- [ ]  `GET listAccountingTitles` API integration on setting page
- [ ]  `POST addAccountingTitleToFavorite` API integration on setting page
- [ ]  `POST removeAccountingTitleFromFavorite` API integration on setting page
- [ ]  `POST addNewSub` API integration on setting page
- [ ]  `POST addNewAccountingTitle` API integration on setting page
- [ ]  `POST updateAccountingTitle` API integration on setting page

### Employee page

- [ ]  `GET listEmployees` API integration on employee page
- [ ]  `POST updateEmployee` API integration on employee page
- [ ]  `POST deleteEmployees` API integration on employee page
-----
- [[FEATURE] - GET company API integration on employee page](https://github.com/CAFECA-IO/iSunFA/issues/1558)
- [[FEATURE] - POST delete company API integration on employee page](https://github.com/CAFECA-IO/iSunFA/issues/1559)
- [[FEATURE] - POST transfer ownership API integration on employee page](https://github.com/CAFECA-IO/iSunFA/issues/1560)
- [[FEATURE] - POST rename company API integration on employee page](https://github.com/CAFECA-IO/iSunFA/issues/1561)
- [[FEATURE] - Team setting modal (desktop & mobile)](https://github.com/CAFECA-IO/iSunFA/issues/1562)
- [[FEATURE] - Layout of procedure of deleting company (estimated according to hypothesis)](https://github.com/CAFECA-IO/iSunFA/issues/1563)
- [[FEATURE] - Layout of procedure of transferring ownership (estimated according to hypothesis)](https://github.com/CAFECA-IO/iSunFA/issues/1564)
- [[FEATURE] - GET listAccountingTitles API integration on setting page](https://github.com/CAFECA-IO/iSunFA/issues/1565)
- [[FEATURE] - POST addAccountingTitleToFavorite API integration on setting page](https://github.com/CAFECA-IO/iSunFA/issues/1566)
- [[FEATURE] - POST removeAccountingTitleFromFavorite API integration on setting page](https://github.com/CAFECA-IO/iSunFA/issues/1567)
- [[FEATURE] - POST addNewSub API integration on setting page](https://github.com/CAFECA-IO/iSunFA/issues/1568)
- [[FEATURE] - POST addNewAccountingTitle API integration on setting page](https://github.com/CAFECA-IO/iSunFA/issues/1569)
- [[FEATURE] - POST updateAccountingTitle API integration on setting page](https://github.com/CAFECA-IO/iSunFA/issues/1570)
- [[FEATURE] - GET listEmployees API integration on employee page](https://github.com/CAFECA-IO/iSunFA/issues/1571)
- [[FEATURE] - POST updateEmployee API integration on employee page](https://github.com/CAFECA-IO/iSunFA/issues/1572)
- [[FEATURE] - POST deleteEmployees API integration on employee page](https://github.com/CAFECA-IO/iSunFA/issues/1573)
- [[FEATURE] - Functionality of SettingCompanyInfoPage (ISFMK00069)](https://github.com/CAFECA-IO/iSunFA/issues/1574)
- [[FEATURE] - Functionality of SettingAccountTitlePage (ISFMK00031) (ISFMK00040)](https://github.com/CAFECA-IO/iSunFA/issues/1575)
- [[FEATURE] - Functionality of Salary - EmployeesList (ISFMK00041)](https://github.com/CAFECA-IO/iSunFA/issues/1576)
- [[FEATURE] - Functionality of Salary - EmployeeDetailPage (ISFMK00064)](https://github.com/CAFECA-IO/iSunFA/issues/1577)

**Comment by arealclimber** [comment]
## iSunFA 完成: 0 pt 剩餘: 69 pt
- [ ] [[FEATURE] - GET company API integration on employee page #1558](https://github.com/CAFECA-IO/iSunFA/issues/1558)  - 3 pt
- [ ] [[FEATURE] - POST delete company API integration on employee page #1559](https://github.com/CAFECA-IO/iSunFA/issues/1559)  - 3 pt
- [ ] [[FEATURE] - POST transfer ownership API integration on employee page #1560](https://github.com/CAFECA-IO/iSunFA/issues/1560)  - 3 pt
- [ ] [[FEATURE] - POST rename company API integration on employee page #1561](https://github.com/CAFECA-IO/iSunFA/issues/1561)  - 3 pt
- [ ] [[FEATURE] - Team setting modal (desktop & mobile) #1562](https://github.com/CAFECA-IO/iSunFA/issues/1562)  - 3 pt
- [ ] [[FEATURE] - Layout of procedure of deleting company (estimated according to hypothesis) #1563](https://github.com/CAFECA-IO/iSunFA/issues/1563)  - 5 pt
- [ ] [[FEATURE] - Layout of procedure of transferring ownership (estimated according to hypothesis) #1564](https://github.com/CAFECA-IO/iSunFA/issues/1564)  - 5 pt
- [ ] [[FEATURE] - GET listAccountingTitles API integration on setting page #1565](https://github.com/CAFECA-IO/iSunFA/issues/1565)  - 3 pt
- [ ] [[FEATURE] - POST addAccountingTitleToFavorite API integration on setting page #1566](https://github.com/CAFECA-IO/iSunFA/issues/1566)  - 3 pt
- [ ] [[FEATURE] - POST removeAccountingTitleFromFavorite API integration on setting page #1567](https://github.com/CAFECA-IO/iSunFA/issues/1567)  - 3 pt
- [ ] [[FEATURE] - POST addNewSub API integration on setting page #1568](https://github.com/CAFECA-IO/iSunFA/issues/1568)  - 3 pt
- [ ] [[FEATURE] - POST addNewAccountingTitle API integration on setting page #1569](https://github.com/CAFECA-IO/iSunFA/issues/1569)  - 3 pt
- [ ] [[FEATURE] - POST updateAccountingTitle API integration on setting page #1570](https://github.com/CAFECA-IO/iSunFA/issues/1570)  - 3 pt
- [ ] [[FEATURE] - GET listEmployees API integration on employee page #1571](https://github.com/CAFECA-IO/iSunFA/issues/1571)  - 3 pt
- [ ] [[FEATURE] - POST updateEmployee API integration on employee page #1572](https://github.com/CAFECA-IO/iSunFA/issues/1572)  - 3 pt
- [ ] [[FEATURE] - POST deleteEmployees API integration on employee page #1573](https://github.com/CAFECA-IO/iSunFA/issues/1573)  - 3 pt
- [ ] [[FEATURE] - Functionality of SettingCompanyInfoPage (ISFMK00069) #1574](https://github.com/CAFECA-IO/iSunFA/issues/1574)  - 2 pt
- [ ] [[FEATURE] - Functionality of SettingAccountTitlePage (ISFMK00031) (ISFMK00040) #1575](https://github.com/CAFECA-IO/iSunFA/issues/1575)  - 5 pt
- [ ] [[FEATURE] - Functionality of Salary - EmployeesList (ISFMK00041) #1576](https://github.com/CAFECA-IO/iSunFA/issues/1576)  - 5 pt
- [ ] [[FEATURE] - Functionality of Salary - EmployeeDetailPage (ISFMK00064) #1577](https://github.com/CAFECA-IO/iSunFA/issues/1577)  - 5 pt

**Comment by arealclimber** [comment]
![image](https://github.com/user-attachments/assets/74889158-8f29-458f-a710-264f8b6aae82)

**Comment by arealclimber** [comment]
project 超過 1200 個，無法新增 project

![CleanShot 2024-07-16 at 13 09 43](https://github.com/user-attachments/assets/95b0e4a3-404e-4966-9165-03fd7c758f4d)

**Comment by arealclimber** [comment]
- [ ] #1575 
- [ ] #1576 
- [ ] #1577 
- [ ] 不在 Alpha release 裡：#1579 
- [ ] #1580

**Comment by arealclimber** [comment]
尚未歸類 project:
- [ ] #1575 
- [ ] #1576 
- [ ] #1577 
- [ ] 不在 Alpha release 裡：#1579 
- [ ] #1580
