### ISSUE TITLE
[FEATURE] - GET company API integration on setting page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1558]
### Summary
Integrate the GET company API on the employee page. This feature ensures the correct fetching of company data for employee management.

### Tasks
- [x] ensure API interfaces
- [x] Implement API integration on the page
- [x] Handle the possible consequences of API response

**Comment by arealclimber** [comment]
took 2 hrs
remaining 2 hrs

**Comment by arealclimber** [comment]
took 2 hrs
done
