### ISSUE TITLE
[FEATURE] - POST delete company API integration on setting page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1559]
### Summary
Integrate the POST delete company API on the employee page. This feature allows for the deletion of a company from the employee management interface.

### Tasks
- [x] ensure API interfaces
- [x] Implement API integration on the page
- [x] Handle the possible consequences of API response

**Comment by arealclimber** [comment]
took 2 hrs
done
