### ISSUE TITLE
[FEATURE] - POST transfer ownership API integration on setting page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1560]
### Summary
Integrate the POST transfer ownership API on the employee page. This feature facilitates the transfer of company ownership within the employee management interface.

### Tasks
- [x] ensure API interfaces
- [x] Implement API integration on the page
- [x] Handle the possible consequences of API response

**Comment by godmmt** [comment]
https://github.com/user-attachments/assets/74889158-8f29-458f-a710-264f8b6aae82

**Comment by godmmt** [comment]
# API Doc 

https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#transferowner

**Comment by godmmt** [comment]
src/components/transfer_company_modal/transfer_company_modal.tsx

**Comment by godmmt** [comment]
https://github.com/CAFECA-IO/Documents/blob/main/ISF/ISF_API_Handler.md

**Comment by godmmt** [comment]
第一次串 API 
需要多一點時間研究

**Comment by godmmt** [comment]
第一次串 ISF API，需要多一點時間研究

**Comment by godmmt** [comment]
- [ ] 改 API 文件

newOwnerId: string

**Comment by godmmt** [comment]
took 3 hours

remain 2

**Comment by godmmt** [comment]
參考 table

user

admin

**Comment by godmmt** [comment]
user id

10000017 qqq
10000018 ttt

**Comment by godmmt** [comment]
10000098	lizphone

10000061	LizCompany	87878787	Taiwan	false	https://storage.googleapis.com/mermer-offical-km/ISunFa/3579fc26-bc47-44a4-b67e-d674d5ef073c.svg	1722220959	1722220959	1722220959	NULL

**Comment by godmmt** [comment]
user:
10000099	lizdermbp	NULL	NULL	NULL	AnOrzo9kNKLS7A-5MFwR0JF0Ci8	MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE-ssuL_FjG2BKWLG_d2ILF6XQS3BRQ6DoAjW4FrrGx3jE8Y4Nn6vJYJXL-FrTmKiSaAYIgNMs37Mk7g5TnbNZNA==	ES256	https://storage.googleapis.com/mermer-offical-km/ISunFa/d4b4887d-290f-4dce-a296-c810d0e2c2c7.svg	1722221073	1722221073	NULL

company:
10000062	LizBigTeam	99990000	Taiwan	false	https://storage.googleapis.com/mermer-offical-km/ISunFa/07bd7eec-b563-4386-83cf-0406868292b9.svg	1722221125	1722221125	1722221125	NULL

admin:
10000171	10000099	10000062	99999993		true	1722221125	NULL	1722221125	1722221125	NULL

**Comment by godmmt** [comment]
有成功打 API 
也收到 success

但好像沒有成功轉移

**Comment by godmmt** [comment]
下午再問問看後端

**Comment by godmmt** [comment]
目前不管 userId 是否存在於資料庫
都會回傳 success

如果要確認是否真的轉移
就看回傳的 `data` 物件
裡面的會有該公司所有的 role 像是 admin 和 owner

<img width="953" alt="截圖 2024-07-29 下午3 47 29" src="https://github.com/user-attachments/assets/18ec276f-f8cb-43b9-a13c-b43f99bc5e8c">

<img width="1042" alt="截圖 2024-07-29 下午3 48 07" src="https://github.com/user-attachments/assets/3b4c20fd-6978-48f6-b125-19ccc2be49fe">

**Comment by godmmt** [comment]
注意：
用 dev 沒辦法好好的測試 API 是否成功
會時常抓不到 selectedCompany
甚至出現過打完 API 沒有反應(request payload 正確的情況下)

所以一定要改成先 build 再 start
不然會頭很痛
像我今天這樣🙂

**Comment by godmmt** [comment]
轉移成功要怎麼通知
用彈窗嗎

**Comment by godmmt** [comment]
payload

interface:

```
src/interfaces/admin.ts
```

**Comment by godmmt** [comment]
轉移成功
給成功彈窗
點擊 ok 後會重新整理網頁 `window.location.reload();`
讓元件拿到最新資料
讓兩個按鈕可以隱藏（Delete Company / Transfer Administration）

**Comment by godmmt** [comment]
- [x] POST transfer ownership API integration on setting page

失敗的部分也給彈窗

使用 Promise .then .catch 來處理彈窗

**Comment by godmmt** [comment]
took 8 hours

Total time: 11.5 hours

done.

**Comment by godmmt** [comment]
時間太晚了，明早會再檢查並且解 PR 衝突
