### ISSUE TITLE
[FEATURE] - POST rename company API integration on setting page

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1561]
### Summary
Integrate the POST rename company API on the employee page. This feature allows renaming a company from the employee management interface.

### Tasks
- [x] ensure API interfaces
- [x] Implement API integration on the page
- [x] Handle the possible consequences of API response

**Comment by arealclimber** [comment]
took 2 hrs
remaining 1.5 hrs

**Comment by arealclimber** [comment]
took 1.5 hrs
done
