### ISSUE TITLE
[FEATURE] - List account-related functionality according to the role information in getCompanyById API

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1678]
### Summary

根據 getCompanyById API 中的角色資訊列出帳戶相關功能

### Tasks

```markdown
- [ ] define and use interfaces in API and frontend
- [ ] show the functionality of role of Owner
- [ ] disable the edit icon if the user isn't Owner
```

### Dependencies

Frontend Framework

**Comment by arealclimber** [comment]
took 2 hrs
done
