### ISSUE TITLE
[FEATURE] - cash flow mapping, 並income statement 需要回傳ratio, 和時間

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#1733]
### Summary

cash flow mapping, 並income statement 需要回傳ratio, 和時間

### Tasks

```markdown
- [ ] 回傳的時間有 preDate, 和curDate
- [ ] income statement 要回傳
- [ ] cash flow mapping RevenueAndExpenseRatio
```

**Comment by TinyMurky** [comment]
took 3 hours
done
