### ISSUE TITLE
[FEATURE] - Enhance the interface and features of financial reports

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#1753]
### Summary

報表上的資料都從 API 來、確保報告顯示跟下載功能正常

### Tasks

```markdown
- [ ] balance sheet
- [ ] income statement
- [ ] cash flow statement
```

### Dependencies

Frontend Framework

**Comment by arealclimber** [comment]
took 4 hrs
remaining 4 hrs

**Comment by arealclimber** [comment]
- [x]  balance sheet 圓餅圖計算 (refer to Murky)
- [x]  balance sheet 確定會計科目
- [x]  報告側邊截圖縮圖
- [x]  用縮圖控制PDF換頁
- [x]  將 PDF 顯示改成用 iframe 顯示
- [x] 下載按鈕改成列印網頁
- 單獨報告頁面需登入跟確認用戶權限之後再顯示 -> 後端負責資料回傳，前端根據資料回傳訊息
- 標注網頁 404 bug，明天修
- income statement, cash flow statement 因為 API 回傳的會計科目跟設計稿不一致，導致有些頁面的排版不符合 A4 高度，需等待回傳資料調整完之後再觀察，另外這兩張表分別有漏接 API 資料的地方，明天跟 @jing12345678910 分工確保串接無誤
- [ ] balance sheet 存貨天數數字從 API 拿

**Comment by arealclimber** [comment]
- [ ] income statement
- [ ] cash flow statement

**Comment by arealclimber** [comment]
took 3.5 hrs
- integrate cash flow API 

done
