### ISSUE TITLE
🐯 iSunFA tasks by Shirley

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#2]
- ref: 
    - [design system](https://www.figma.com/design/jgDW7ljfQ0RGvnebW9ve0h/iSunFA-Design-System?node-id=4%3A4&m=dev)｜[Landing page mockup](https://www.figma.com/file/4PS1QfFhlwIrJ5WwyDcWws/iSunFA?type=design&node-id=79-260&mode=design&t=7gQAR85WllzjD6DO-0)｜[users page mockup](https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=4-369&mode=dev)（[mobile](https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=811%3A111363&mode=dev)）｜
    - [規劃 iSunFA 開發時程跟開票](https://github.com/CAFECA-IO/iSunFA/issues/113) ｜[開發分工白板](https://app.heptabase.com/w/2bc389441bf4794e08d64cf88dd29168e018560766feb4ee1d20a1af18fbbf58)｜
-----

- [ ] CAFECA-IO/iSunFA#62
- [ ] CAFECA-IO/iSunFA#106
- [x] CAFECA-IO/iSunFA#110
- [x] CAFECA-IO/iSunFA#111
- [x] CAFECA-IO/iSunFA#147
- [x] CAFECA-IO/iSunFA#163
- [x] CAFECA-IO/iSunFA#212
- [x] CAFECA-IO/iSunFA#213
- [x] CAFECA-IO/iSunFA#639
- [ ] CAFECA-IO/iSunFA#641
- [ ] CAFECA-IO/iSunFA#642
- [ ] CAFECA-IO/iSunFA#882
- [x] CAFECA-IO/iSunFA#884
- [x] CAFECA-IO/iSunFA#952
- [x] CAFECA-IO/iSunFA#953
- [x] CAFECA-IO/iSunFA#960
- [x] CAFECA-IO/iSunFA#965
- [x] CAFECA-IO/iSunFA#982
- [x] CAFECA-IO/iSunFA#994
- [x] CAFECA-IO/iSunFA#995
- [x] CAFECA-IO/iSunFA#1003
- [x] CAFECA-IO/iSunFA#1039
- [x] CAFECA-IO/iSunFA#1042
- [x] CAFECA-IO/iSunFA#1043
- [x] CAFECA-IO/iSunFA#1044
- [x] CAFECA-IO/iSunFA#1028
- [x] CAFECA-IO/iSunFA#1048
- [x] CAFECA-IO/iSunFA#1064
- [x] CAFECA-IO/iSunFA#1072
- [x] CAFECA-IO/iSunFA#1073
- [x] CAFECA-IO/iSunFA#1089
- [x] CAFECA-IO/iSunFA#1184
- [x] CAFECA-IO/FAITH#43
- [x] CAFECA-IO/iSunFA#1256
- [x] CAFECA-IO/faith#2
- [ ] https://github.com/CAFECA-IO/iSunFA/issues/1445
- [x] #1557

-----
## Beyond the Alpha release
- [ ]  #1579

**Comment by arealclimber** [comment]
- [x] CAFECA-IO/iSunFA#75
- [x] CAFECA-IO/iSunFA#88
- [x] CAFECA-IO/iSunFA#109
- [x] CAFECA-IO/iSunFA#107
- [x] CAFECA-IO/iSunFA#108
- [x] CAFECA-IO/iSunFA#262
- [x] CAFECA-IO/iSunFA#326
- [x] CAFECA-IO/iSunFA#358
- [x] CAFECA-IO/iSunFA#363
- [x] CAFECA-IO/iSunFA#364
- [x] CAFECA-IO/iSunFA#369
- [x] CAFECA-IO/iSunFA#203
- [x] CAFECA-IO/iSunFA#206
- [x] CAFECA-IO/iSunFA#207
- [x] CAFECA-IO/iSunFA#640
- [x] CAFECA-IO/iSunFA#377
- [x] CAFECA-IO/KnowledgeManagement#129
- [x] CAFECA-IO/iSunFA#462
- [x] CAFECA-IO/iSunFA#469
- [x] CAFECA-IO/iSunFA#471
- [x] CAFECA-IO/iSunFA#509
- [x] CAFECA-IO/iSunFA#533
- [x] CAFECA-IO/iSunFA#548
- [x] CAFECA-IO/iSunFA#577
- [x] CAFECA-IO/iSunFA#578
- [x] CAFECA-IO/iSunFA#595
- [x] CAFECA-IO/iSunFA#626
- [x] CAFECA-IO/iSunFA#627
- [x] CAFECA-IO/iSunFA#628
- [x] CAFECA-IO/iSunFA#636
- [x] CAFECA-IO/iSunFA#637
- [x] CAFECA-IO/iSunFA#638
- [x] CAFECA-IO/iSunFA#644
- [x] CAFECA-IO/iSunFA#1 
- [x] CAFECA-IO/iSunFA#5
- [x] CAFECA-IO/iSunFA#7
- [x] CAFECA-IO/iSunFA#8
- [x] CAFECA-IO/iSunFA#9
- [x] CAFECA-IO/iSunFA#10
- [x] CAFECA-IO/iSunFA#11
- [x] CAFECA-IO/iSunFA#12
- [x] CAFECA-IO/iSunFA#13
- [x] CAFECA-IO/iSunFA#14
- [x] CAFECA-IO/iSunFA#17
- [x] CAFECA-IO/iSunFA#22
- [x] CAFECA-IO/iSunFA#74
- [x] #886
- [x] #902
- [x] #919
- [x] #925
- [x] CAFECA-IO/iSunFA#679
- [x] CAFECA-IO/iSunFA#690
- [x] CAFECA-IO/iSunFA#699
- [x] CAFECA-IO/iSunFA#700
- [x] CAFECA-IO/iSunFA#704
- [x] CAFECA-IO/iSunFA#717
- [x] CAFECA-IO/iSunFA#737
- [x] CAFECA-IO/iSunFA#738
- [x] CAFECA-IO/iSunFA#759
- [x] CAFECA-IO/iSunFA#769
- [x] CAFECA-IO/iSunFA#770
- [x] CAFECA-IO/iSunFA#815
- [x] CAFECA-IO/iSunFA#835
- [x] CAFECA-IO/iSunFA#863
- [x] CAFECA-IO/iSunFA#862
- [x] CAFECA-IO/iSunFA#865
- [x] CAFECA-IO/iSunFA#866

**Comment by arealclimber** [comment]
- [x] CAFECA-IO/iSunFA#80
- [x] CAFECA-IO/iSunFA#112
- [x] CAFECA-IO/iSunFA#113
- [x] CAFECA-IO/iSunFA#114
- [x] CAFECA-IO/iSunFA#129
- [x] CAFECA-IO/iSunFA#138
- [x] CAFECA-IO/KnowledgeManagement#121
- [x] CAFECA-IO/iSunFA#650
- [x] CAFECA-IO/KnowledgeManagement#151
- [x] CAFECA-IO/iSunFA#263
- [x] CAFECA-IO/iSunFA#374
