### ISSUE TITLE
[FEATURE] - (FE: Beta) iSunFA登入流程修改 - 需求確認與規劃

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#2018]
### Summary

確認設計稿和前端需求，規劃工作內容和進度 

### Tasks

- [x] 查看設計稿，確認 Apple 和 Google 登入的 UI 設計和用戶流程。
- [x] 確定前端需要實現的功能和頁面，包括錯誤處理、狀態管理等。
- [x] 與後端工程師討論 API 的需求，確保兩者可以共用一個認證 API。
- [x] 開票

### Dependencies

Frontend Framework

### Additional Notes

[設計稿](https://www.figma.com/design/er65BjKRQhYLBDnYPSL3I4/iSunFA-Mockup-(Beta)?node-id=7034-212180&t=LI1Xygb8NemBYXLj-0)

**Comment by TzuHanLiang** [comment]
還未與 backend 確認接口
took 1hrs
