### ISSUE TITLE
[FEATURE] - (FE: Beta) iSunFA登入流程修改 - 選擇第三方庫與 SDK

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#2019]
### Summary

選擇支持 Apple 和 Google 登入的第三方庫或 SDK，並配置與 Next.js 的集成，確保兩者可以共用相同的 API 結構

### Tasks

- [x] 研究並比較各種支持 OAuth 2.0 的第三方庫，如 next-auth、passport.js 或其他適合 Next.js 的解決方案。
- [x] 確認選擇的庫能夠支持同時處理 Apple 和 Google 的 OAuth 流程。
- [x] 在 Next.js 專案中安裝並配置選定的庫，確保它能夠與 Next.js 頁面和 API 路由整合。
- [x] 配置環境變量和必要的 OAuth 設定，如客戶端 ID、秘密金鑰等。

### Dependencies

Frontend Framework

### Additional Notes

[設計稿](https://www.figma.com/design/er65BjKRQhYLBDnYPSL3I4/iSunFA-Mockup-(Beta)?node-id=7034-212180&t=LI1Xygb8NemBYXLj-0)

**Comment by TzuHanLiang** [comment]
選擇使用 next-auth，目前 google 必要的 OAuth 設定已由 Luphia 提供，apple 設定還沒有
took 2hrs

**Comment by TzuHanLiang** [comment]
took 1hrs
done
----
Apple 相關設定在 #2021 裡面實作
