### ISSUE TITLE
[FEATURE] - (FE: Beta) iSunFA登入流程修改 - 實作通用認證邏輯

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#2020]
### Summary

開發通用的登入邏輯和 API 對接層，確保 Apple 和 Google 登入都通過相同的流程和 API 進行認證

### Tasks
- [x] 在 Next.js 專案中創建一個通用的登入邏輯模塊，這個模塊應該能處理 Apple 和 Google 的認證請求。
- [x] 編寫前端與後端 API 的接口邏輯，確保能夠處理從 OAuth 提供者返回的認證數據。
- [x] 實作通用的狀態管理邏輯，以處理不同的登入狀態，如成功、失敗、或用戶取消操作等。
- [x] 測試這個通用邏輯模塊，確保它可以正確處理兩種認證流程並返回相應的結果。

### Dependencies

Frontend Framework

### Additional Notes

[設計稿](https://www.figma.com/design/er65BjKRQhYLBDnYPSL3I4/iSunFA-Mockup-(Beta)?node-id=7034-212180&t=LI1Xygb8NemBYXLj-0)

**Comment by TzuHanLiang** [comment]
- #2072 
- took 8+hrs
- done
