### ISSUE TITLE
[FEATURE] - (FE: Beta) iSunFA登入流程修改 - 實作 Google 登入

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#2022]
### Summary

實作 Google 登入按鈕 (UI)，並集成到通用認證邏輯中

### Tasks
- [x] 根據設計稿實作 Google 登入按鈕的前端 UI，確保其符合設計要求並具有響應式設計。
- [x] 將該按鈕與通用認證邏輯相連接，觸發 Google 的認證流程。
- [x] 測試按鈕的功能，確保點擊後能正常啟動 Google 登入流程，並返回正確的結果。

### Dependencies

Frontend Framework

### Additional Notes

[設計稿](https://www.figma.com/design/er65BjKRQhYLBDnYPSL3I4/iSunFA-Mockup-(Beta)?node-id=7034-212180&t=LI1Xygb8NemBYXLj-0)

**Comment by TzuHanLiang** [comment]
took 1.5hrs
完成 basic UI

**Comment by TzuHanLiang** [comment]
took 3hrs
done at 0814
