### ISSUE TITLE
[FEATURE] - Modify the result of post ocr based on the refined uploading process

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#2075]
### Summary

根據修改後上傳流程修改post ocr結果，目的在於提升用戶體驗

### Tasks

# 後端
- [ ]  API POST `api/v1/company/[companyId]/ocr` request body 的 `formData` 從 `image` 改成 `image, imageName, imageSize, uploadIdentifier`
- [ ]  API POST `api/v1/company/[companyId]/ocr` response 改成回傳 `IOCR`
- [ ]  `IOCR` 需修改，並且 `imageName, imageSize, uploadIdentifier` 由前端傳入，後端不需要修改這三個值
    ```tsx    
    export interface IOCR {
      id: number;
      aichResultId: string;
      imageName: string; // Info: from frontend (20240815 - Shirley)
      imageUrl: string;
      imageSize: string; // Info: from frontend (20240815 - Shirley)
      progress: number; // 0 ~ 100 Float
      status: ProgressStatus;
      createdAt: number;
      uploadIdentifier?: string; // Info: from frontend (20240815 - Shirley)
    }
    
    ```

# 前端

- _Originally posted by @arealclimber in https://github.com/CAFECA-IO/iSunFA/issues/2057#issuecomment-2288382520_
- _Originally posted by @arealclimber in https://github.com/CAFECA-IO/iSunFA/issues/2057#issuecomment-2290309043_
- [x] 在 `IOCR` interface 上新增一個 `propertyA` 去判斷檔案是否上傳成功
- [x] 在 accounting context 裡區分 pendingOCRList 跟 uploadedOCRList ，透過比對兩個 OCRList 的 `propertyA` 來檢查 skeleton file list 是否需要減少
- [x] 在 post request 成功之後，需直接在 pendingOCRList 刪掉對應 `propertyA`，並且轉移到 uploadedOCRList（代表需要後端在 post request 成功後回傳完整 `IOCR` interface）
- [x] 在 pending 時，OCR item 保留 file name 跟 file size，也就是由前端決定 uploadIdentifier, fileName, fileSize，以滿足在上傳如 PDF 檔案時，無法產生縮圖或AI辨識失敗時，能讓用戶知道特定檔案的上傳紀錄
-----
- TODO: 考慮上傳超過檔案大小限制的情形，前端畫面要提示用戶
----

### Dependencies

API Availability, Backend Support, Frontend Framework

**Comment by arealclimber** [comment]
![CleanShot 2024-08-15 at 18 18 08](https://github.com/user-attachments/assets/f01427dd-24ec-4f46-a805-f4a010a6808d)

**Comment by arealclimber** [comment]
前端傳入 image, imageSize, imageName, uploadIdentifier
![CleanShot 2024-08-15 at 18 18 08](https://github.com/user-attachments/assets/f01427dd-24ec-4f46-a805-f4a010a6808d)

**Comment by TinyMurky** [comment]
後端更改完成，目前會接收前端傳入的formData之後存入Data base 並回傳IOCR
但是上傳的一瞬間會是紅色的圖案
![2024-08-16_13-40](https://github.com/user-attachments/assets/e91f9516-e2d3-408c-8ba1-95740f62eb82)
![upload](https://github.com/user-attachments/assets/93042e74-d1dd-4fdb-b266-57eba0750fd8)

**Comment by TinyMurky** [comment]
took 2 hours
done!

**Comment by TinyMurky** [comment]
![upload pdf](https://github.com/user-attachments/assets/f9e4976c-5d43-4168-bc44-eb6e35131e74)
