### ISSUE TITLE
[FEATURE] - Write Docker compose for whole ISunfa

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#2102]
### Summary

Write Docker compose for whole ISunfa

### Tasks

- [ ] Dockerfile for each project
  - [ ]  isunfa
  - [ ] ollama
  - [ ] qdrain
  - [ ] faith
  - [ ] aich
  - [ ] db postgres need volumn
  - [ ] nginx
- [ ] env file for each project
- [ ] nginx for reverse proxy
- [ ] docker compose

**Comment by RexBearIU** [comment]
It takes 4.5 hours.

Finish isunfa and aich part 

need to let env be successfully loaded

done

**Comment by RexBearIU** [comment]
It takes 4 hours.

Can docker compose whole service. but stiil need env and path setting.

need to extract more issue ticket.

**Comment by RexBearIU** [comment]
Additional issue
https://github.com/CAFECA-IO/iSunFA/issues/2174
https://github.com/CAFECA-IO/iSunFA/issues/2175
https://github.com/CAFECA-IO/iSunFA/issues/2171
https://github.com/CAFECA-IO/iSunFA/issues/2170
