### ISSUE TITLE
[FEATURE] - 移除所有 eslint-disable 註解

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#2116]
### Summary

將所有 eslint-disable 的程式碼改寫，並將註解移除

### Tasks

-

**Comment by jing12345678910** [comment]
任務：把eslint-disable相關的註解拿掉後，解決相關錯誤
<img width="311" alt="image" src="https://github.com/user-attachments/assets/cb198225-559e-47f3-86e5-e75f7bdf6586">

**Comment by jing12345678910** [comment]
剩餘eslint-disable的種類

- [ ] // eslint-disable-next-line import/no-extraneous-dependencies
- [ ] // eslint-disable-next-line import/no-cycle
- [ ] // eslint-disable-next-line @typescript-eslint/no-explicit-any
- [ ] // eslint-disable-next-line jsx-a11y/label-has-associated-control
- [ ] // eslint-disable-next-line no-promise-executor-return
- [ ] // eslint-disable-next-line @typescript-eslint/no-unused-vars
- [ ] // eslint-disable-next-line no-nested-ternary
- [ ] // eslint-disable-next-line tailwindcss/no-arbitrary-value
- [ ] // eslint-disable-next-line tailwindcss/migration-from-tailwind-2
- [ ] // eslint-disable-next-line tailwindcss/no-unnecessary-arbitrary-value, tailwindcss/no-arbitrary-value
- [ ] // eslint-disable-next-line implicit-arrow-linebreak
- [ ] // eslint-disable-next-line function-paren-newline
- [ ] // eslint-disable-next-line react/no-array-index-key
- [ ] // eslint-disable-next-line react/jsx-curly-newline
- [ ] // eslint-disable-next-line react/jsx-boolean-value
- [ ] // eslint-disable-next-line react/jsx-no-constructed-context-values
- [ ] // eslint-disable-next-line react/prop-types
- [ ] // eslint-disable-next-line no-unused-vars
- [ ] // eslint-disable-next-line no-console
- [ ] // eslint-disable-next-line no-param-reassign
- [ ] // eslint-disable-next-line no-restricted-syntax
- [ ] // eslint-disable-next-line no-bitwise
- [ ] // eslint-disable-next-line no-continue
- [ ] // eslint-disable-next-line no-restricted-globals

**Comment by jing12345678910** [comment]
原本：
useEffect(() => {
    const addedBookmark = Object.entries(bookmarkList)
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      .filter(([key, value]) => value.added)
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      .map(([key, value]) => key);

    setSelectedBookmark(addedBookmark);
  }, [isAddBookmarkModalVisible]);
  
  改成：
   useEffect(() => {
    const addedBookmark = Object.entries(bookmarkList)
      .filter(([, value]) => value.added)
      .map(([key]) => key);

    setSelectedBookmark(addedBookmark);
  }, [isAddBookmarkModalVisible]);
  
  說明：
  在 JavaScript 和 TypeScript 中，使用解構賦值時，如果只需要對象或數組的一部分，可以使用逗號 , 來跳過未使用的變數。例如，使用 .filter(([key, value]) => ...) 時，如果只需要 value 而不需要 key，可以這樣寫 ([, value]) => ...。

保留逗號 , 是為了告訴編譯器或解譯器這個變數被跳過，而不是刪除逗號。

**Comment by jing12345678910** [comment]
原本：
```
<button
        type="button"
        // TODO: (20240517 - Shirley) [Beta] temp disabled
        // eslint-disable-next-line react/jsx-boolean-value
        disabled={true}
        className="flex w-full items-center gap-16px px-24px py-10px text-button-text-secondary disabled:text-button-text-disable disabled:hover:text-button-text-secondary"
      >
```
改成：
```
  <button
        type="button"
        // TODO: (20240517 - Shirley) [Beta] temp disabled
        disabled
        className="flex w-full items-center gap-16px px-24px py-10px text-button-text-secondary disabled:text-button-text-disable disabled:hover:text-button-text-secondary"
      >
```
說明：
react/jsx-boolean-value 規則要求在 JSX 中，如果屬性是布爾值 true，應該省略其值。例如，應該將 disabled={true} 簡化為 disabled

**Comment by jing12345678910** [comment]
原本：
```
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const file = new File([blob as any], 'canvas-image.png', { type: 'image/png' });
```
改成：
`   const file = new File([blob as Blob], 'canvas-image.png', { type: 'image/png' });`
說明：
**Blob 類型的特點：**
不可變：blob 是 JavaScript 中的一種物件類型，是一種不可變的數據塊，內容無法被直接修改，類似於文件的原始數據。
二進制數據：Blob 儲存的是二進制數據，可以是文本、圖像、視頻等。

**Blob 物件兩個重要屬性：**
size：表示 Blob 物件的大小，以字節為單位。
type：表示 Blob 的 MIME 類型，如 image/png 或 text/plain。

**什麼時候會用到 Blob？**
文件操作：可以通過 File 物件來創建一個文件，Blob 是其基礎類型。
傳輸二進制數據：Blob 可以用來傳輸文件或圖片等二進制數據，例如通過 fetch API 下載文件並轉換為 Blob 以便保存或顯示。
生成文件：例如，可以將canvas的內容轉換為 Blob，然後將它保存為圖像文件。

**示例代碼：**
將 canvas 轉換為 Blob 並創建一個文件的簡單例子：

canvas.toBlob(function(blob) {
  const file = new File([blob], 'canvas-image.png', { type: 'image/png' });
  console.log(file);
});
在這個例子中，blob 就是一個 Blob 物件，包含了 canvas 上的圖像數據。隨後，這個 Blob 被用來創建一個 File 物件，並且指定了文件名和 MIME 類型。

**Comment by jing12345678910** [comment]
原本：
```
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const g: any =
    typeof globalThis === 'object'
      ? globalThis
      : typeof window === 'object'
        ? window
        : typeof global === 'object'
          ? global
          : null; // Info: (20240409 - Shirley) Causes an error on the next line

  g.globalContext = context;
```
改成：

**Comment by jing12345678910** [comment]
原本：
```
  const value = {
    bookmarkList: bookmarkListRef.current,
    addSelectedBookmarks,
  };
```

改成：
```
   const value = useMemo(() => ({
     bookmarkList: bookmarkListRef.current,
     addSelectedBookmarks,
   }), [bookmarkListRef.current, addSelectedBookmarks]);
```

說明：
出現以下錯誤，所以改用useMemo
The 'value' object (at line 708) passed as the value prop to the Context provider (at line 713) changes every render. To fix this consider wrapping it in a useMemo hook.eslint[react/jsx-no-constructed-context-values](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-no-constructed-context-values.md)

**Comment by jing12345678910** [comment]
在專案中有許多eslint-disable-next-line import/no-cycle註解
<img width="354" alt="image" src="https://github.com/user-attachments/assets/5b4e1a69-fd80-4ea5-9f0b-0b04d327a4c4">

**Comment by jing12345678910** [comment]
// eslint-disable-next-line react/prop-types
// eslint-disable-next-line no-restricted-syntax
// eslint-disable-next-line no-bitwise
// eslint-disable-next-line no-continue
// eslint-disable-next-line no-restricted-globals
// eslint-disable-next-line no-underscore-dangle

**Comment by jing12345678910** [comment]
// eslint-disable-next-line react/prop-types 註解不需要移除的原因，是因為專案使用 TypeScript，而不是 JavaScript。TypeScript 本身已經有型別檢查系統，不需要再額外使用 prop-types 來做屬性檢查。react/prop-types 這個 ESLint 規則是為了確保在 JavaScript 中有使用 PropTypes 做型別檢查，而在 TypeScript 中，這些型別已經由 TypeScript 的 interface 或 type 處理。

因此，專案使用 TypeScript時，這個規則是多餘的，因為 TypeScript 已經負責確保屬性型別的正確性。因為 ESLint 不需要針對 TypeScript 檔案強制使用 prop-types。

**Comment by jing12345678910** [comment]
// eslint-disable-next-line no-restricted-syntax這個註解不需要移除的原因，是因為使用了 for...in 語法進行迭代，而 ESLint 的 no-restricted-syntax 規則會建議避免使用這個語法，因為它會遍歷物件原型上的屬性，這在某些情況下會導致意想不到的行為。然而，這種語法在某些特定情況下是必要的，尤其是在不影響程式行為的前提下，例如迭代需要處理的物件屬性。

```
 for (const key in data) {
      if (data[key].id === fileId) {
        newData = {
          ...data,
          [key]: {
            id: undefined,
            file: undefined,
          },
        };
        break;
      }
    }
```
使用了 for...in 語法來遍歷 localStorage 中儲存的檔案資料：這段代碼的目的是遍歷 data 物件的所有屬性，找出匹配 fileId 的項目，並更新該項目的 id 和 file。

在這個情境下，使用 for...in 是合理的，因為你正在遍歷物件的所有可枚舉屬性，而 for...in 是專門用來這樣做的。雖然 for...in 會遍歷物件的所有可枚舉屬性，包括原型鏈上的屬性，但如果 data 僅僅是一個普通的 JavaScript 物件（例如從 localStorage 中獲取的物件），這種遍歷方式並不會帶來太大的風險。

**Comment by jing12345678910** [comment]
// eslint-disable-next-line no-bitwise是必要的，因為位元運算（bitwise operations）在這裡是解決問題的唯一有效方式，特別是在處理數學運算或底層操作時。具體來說，這段代碼涉及 Galois Fields（伽羅瓦域）的運算，這是一種常見於編碼理論和加密算法的數學結構。

在這個上下文中，x <<= 1 是一種位元左移操作，這種操作是進行二進制位移的高效方式，通常用來乘以 2。x ^= primitive 代表 XOR 操作（位元異或），是 Galois Fields 運算中的一個關鍵步驟，用來確保結果保持在有限域內。位元運算能夠高效地進行這些計算，沒有其他更好的替代方案。因此，這些操作在這裡是必要的。

因此，保留 no-bitwise 註解是為了告訴 ESLint，這裡的位元運算是合理且必要的，不應該被禁用。

**Comment by jing12345678910** [comment]
// eslint-disable-next-line no-continue 是必要的，原因是 continue 語句在這裡能夠有效地控制迴圈的流程，避免不必要的邏輯處理。在某些情況下，continue 可以幫助跳過當前迴圈的後續部分，進入下一次迴圈，從而提高代碼的可讀性和執行效率。

```
if (fX === 0) {
  fX = coefficients[i];
  // eslint-disable-next-line no-continue
  continue;
}
```
這裡使用 continue 來跳過 fX 還是 0 的情況，直接進入下一次迴圈。這樣做可以避免在 fX === 0 時進行不必要的位元運算和其他操作。

保留 no-continue 註解的原因是告訴 ESLint，continue 在這裡是必須的，不應被禁用。

**Comment by jing12345678910** [comment]
1.
```
window.onmessage = async (event: MessageEvent<FetchRequestData>) => {
  const { apiConfig, options, action } = event.data;

  if (action === Action.CANCEL) {
    if (activeRequest === apiConfig.name && controller) {
      controller.abort();
      controller = null;
      setTimeout(() => {
        // eslint-disable-next-line no-restricted-globals
        window.close();
      }, 1000);
    }
    return;
  }

  await handleRequest(apiConfig, options);
};
```
2.
```
self.onmessage = async (event: MessageEvent<FetchRequestData>) => {
  const { apiConfig, options, action } = event.data;

  if (action === Action.CANCEL) {
    if (activeRequest === apiConfig.name && controller) {
      controller.abort();
      controller = null;
      setTimeout(() => {
        // eslint-disable-next-line no-restricted-globals
        self.close();
      }, 1000);
    }
    return;
  }

  await handleRequest(apiConfig, options);
};
```
這兩個寫法的主要差別在於使用了不同的對象 (window 和 self) 來註冊 onmessage 事件處理器。

> window.onmessage:

window 代表的是整個瀏覽器窗口（或是 tab）。
這種寫法通常在主線程（主頁面）中使用，用於處理主頁面和其他窗口或 iframe 之間的通信。

> self.onmessage:

self 代表的是當前執行上下文，在 Web Worker 中，self 指代的是 Worker 實例本身。
當代碼運行在一個 Web Worker 裏時，self 是對象的正確引用，因為在 Web Worker 中沒有 window 對象。
差異與用途
主頁面（window）:
如果代碼運行在主頁面中（如瀏覽器的主線程），使用 window.onmessage 更合適。
Web Worker（self）:
如果代碼運行在 Web Worker 中（如在背景中處理任務），使用 self.onmessage 是正確的選擇，因為 Web Worker 沒有 window 對象。
結論
如果在主頁面（主線程）中運行代碼，應使用 window；如果代碼在 Web Worker 中運行，應使用 self。

**Comment by jing12345678910** [comment]
// eslint-disable-next-line no-underscore-dangle應該保留
```
  projectLists.forEach((project) => {
    const match = incomeExpensesLists.find(
      (incomeExpense) => incomeExpense.projectId === project.id
    );
    if (match) {
      categories.push(project.name);
      // Info: (20240527 - Gibbs) add eslint-disable-next-line no-underscore-dangle for prisma groupBy function
      // eslint-disable-next-line no-underscore-dangle
      income.push(match._sum.income!);
      // Info: (20240527 - Gibbs) add eslint-disable-next-line no-underscore-dangle for prisma groupBy function
      // eslint-disable-next-line no-underscore-dangle
      expense.push(match._sum.expense!);
    }
  });
```
由於這裡使用的 Prisma 套件，它的某些方法（如 groupBy）會自動生成帶有底線（underscore）的屬性名，例如 _sum。這是 Prisma 的內部命名慣例，無法避免使用帶有底線的屬性。因此，no-underscore-dangle 規則會對這些屬性報錯，但這些底線屬性是 Prisma 本身生成的，屬於其正常行為。

因此，這個 ESLint 註解是必要的，以防止 ESLint 對這些合法屬性名報錯。

**Comment by jing12345678910** [comment]
took 8 hrs
done
