### ISSUE TITLE
[FEATURE] - Optimize PR #2061

### ISSUE THREAD

**Issue by jing12345678910** [CAFECA-IO/iSunFA#2134]
### Summary

[FEATURE] - Optimize PR #2061

### Tasks

PR #2061
The global eslint-disable cannot be used.
The translation module should be used for the text. Strings cannot be typed directly.
The single-line eslint-disable must be added with a deprecation annotation.

**Comment by jing12345678910** [comment]
took 5 hrs

PR https://github.com/CAFECA-IO/iSunFA/pull/2061

- [X] The global eslint-disable cannot be used.
- [X] The translation module should be used for the text. Strings cannot be typed directly.
- [X] The single-line eslint-disable must be added with a deprecation annotation.

done
