### ISSUE TITLE
[DOCS] - api 文件檢查與實際程式碼一致-4

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/iSunFA#2135]
### Summary

api 文件檢查與實際程式碼一致

### Tasks

延續 https://github.com/CAFECA-IO/iSunFA/issues/2068
api 文件檢查與實際程式碼一致
https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0

### Additional Notes

```markdown
project
• P020001 - GET /company/:companyId/project - ISFMK00017
• P020002 - POST /company/:companyId/project
• P021001 - GET /company/:companyId/project/:projectId - ISFMK00033, ISFMK00006
• P021002 - PUT /company/:companyId/project/:projectId - ISFMK00061
• P021003 - DELETE /company/:companyId/project/:projectId
• P024001 - GET /company/:companyId/project/:projectId/milestone - ISFMK00033
• P024002 - PUT /company/:companyId/project/:projectId/milestone - ISFMK00033, ISFMK00061
```

**Comment by gibbs-shih** [comment]
project
- [ ]  P020001 - GET /company/:companyId/project - ISFMK00017
- [ ]  P020002 - POST /company/:companyId/project
- [ ]  P021001 - GET /company/:companyId/project/:projectId - ISFMK00033, ISFMK00006
- [ ]  P021002 - PUT /company/:companyId/project/:projectId - ISFMK00061
- [ ]  P021003 - DELETE /company/:companyId/project/:projectId
- [ ]  P024001 - GET /company/:companyId/project/:projectId/milestone - ISFMK00033
- [ ]  P024002 - PUT /company/:companyId/project/:projectId/milestone - ISFMK00033, ISFMK00061

**Comment by gibbs-shih** [comment]
修改：
• [P024001](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#getMilestone) - GET /company/:companyId/project/:projectId/milestone - ISFMK00033
• [P024002](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0#updateMilestone) - PUT /company/:companyId/project/:projectId/milestone - ISFMK00033, ISFMK00061

**Comment by gibbs-shih** [comment]
take 4 hr
