### ISSUE TITLE
檢查 DB 文件與實際資料庫一致

### ISSUE THREAD

**Issue by gibbs-shih** [CAFECA-IO/iSunFA#2136]
### Summary

檢查 DB 文件與實際資料庫一致

### Tasks

檢查 DB 文件與實際資料庫一致

**Comment by gibbs-shih** [comment]
dictionary
- [ ] 'account'
- [ ] 'admin'
- [ ] 'asset'
- [ ] 'audit_report'
- [ ] 'authentication'
- [ ] 'client'
- [ ] 'company'
- [ ] 'company_kyc'
- [ ] 'company_setting'
- [ ] 'contract'
- [ ] 'department'
- [ ] 'employee'
- [ ] 'employee_project'
- [ ] 'income_expense'
- [ ] 'invitation'
- [ ] 'invoice'
- [ ] 'journal'
- [ ] 'line_item'
- [ ] 'milestone'
- [ ] 'ocr'
- [ ] 'order'
- [ ] 'payment'
- [ ] 'payment_record'
- [ ] 'plan'
- [ ] 'project'
- [ ] 'report'
- [ ] 'role'
- [ ] 'salary_record'
- [ ] 'salary_record_project_hour'
- [ ] 'sale'
- [ ] 'subscription'
- [ ] 'user'
- [ ] 'user_agreement'
- [ ] 'value'
- [ ] 'voucher'
- [ ] 'voucher_salary_record'
- [ ] 'voucher_salary_record_folder'
- [ ] 'work_rate'

關聯圖

**Comment by gibbs-shih** [comment]
修改：
account
admin
company
company_kyc
income_expense


新增：
authentication

**Comment by gibbs-shih** [comment]
take 5 hr

**Comment by gibbs-shih** [comment]
take 5 hr
