### ISSUE TITLE
[DOCS] - 規劃 Beta 「發票功能」點數和開票 

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#2367]
### Summary

規劃 iSunFA Beta 「發票功能」的點數，並開票

### Tasks

- [Wireframe](https://www.figma.com/design/GAcDZhQtnuX6ztMu1adsKm/iSunFA-Wireframe(Beta)?node-id=2-4&m=dev)

### Dependencies

Frontend Framework

**Comment by TzuHanLiang** [comment]
took 6.5hrs
done

**Comment by TzuHanLiang** [comment]
- [ ] [[FEATURE] - [UI] Certificate List - Upload Area #2376](https://github.com/CAFECA-IO/iSunFA/issues/2376) - 3pt
  - [ ] [[FEATURE] - [共用][UI] - Tabs #2377](https://github.com/CAFECA-IO/iSunFA/issues/2377) - 2pt
  - [ ] [[FEATURE] - [共用][UI] - Filters Section #2378](https://github.com/CAFECA-IO/iSunFA/issues/2378) - 5pt
  - [ ] [[FEATURE] - [UI] Certificate List - 樣式控制按鈕 #2379](https://github.com/CAFECA-IO/iSunFA/issues/2379) - 1pt
  - [ ] [[FEATURE] - [UI] Certificate 清單工具列 #2380](https://github.com/CAFECA-IO/iSunFA/issues/2380) - 2pt
  - [ ] [[FEATURE] - [UI] Certificate List - List Item #2381](https://github.com/CAFECA-IO/iSunFA/issues/2381) - 3pt
  - [ ] [[FEATURE] - [UI] Certificate List - 編輯 Certificate #2382](https://github.com/CAFECA-IO/iSunFA/issues/2382) - 5pt
  - [ ] [[FEATURE] - [UI] Certificate List - table #2383](https://github.com/CAFECA-IO/iSunFA/issues/2383) - 3pt
  - [ ] [[FEATURE] - [UI] Certificate List - table item #2390](https://github.com/CAFECA-IO/iSunFA/issues/2390) - 3pt
  - [ ] [[FEATURE] - [UI] Certificate List - Certificate 上傳進度的懸浮窗口 #2384](https://github.com/CAFECA-IO/iSunFA/issues/2384) - 2pt
  - [ ] [[FEATURE] - [UI] Certificate List - Certificate 上傳進度的進度條 #2391](https://github.com/CAFECA-IO/iSunFA/issues/2391) - 2pt
  - [ ] [[FEATURE] - [UI] Voucher-[voucherId] 關聯 Certificate #2397](https://github.com/CAFECA-IO/iSunFA/issues/2397) - 2pt
  - [ ] [[FEATURE] - [UI] Voucher-[voucherId] 關聯 Certificate - 發票預覽 #2398](https://github.com/CAFECA-IO/iSunFA/issues/2398) - 2pt
  - [ ] [[FEATURE] - [UI] Add New Voucher - 選擇 Certificate 區域 #2387](https://github.com/CAFECA-IO/iSunFA/issues/2387) - 3pt
  - [ ] [[FEATURE] - [UI] Add New Voucher - 彈出視窗 - 選擇 Certificate #2393](https://github.com/CAFECA-IO/iSunFA/issues/2393) - 5pt
  - [ ] [[FEATURE] - [UI] Add New Voucher - 彈出視窗 - 上傳 Certificate 顯示進度以及相關控制按鈕 #2396](https://github.com/CAFECA-IO/iSunFA/issues/2396) - 3pt
  - [ ] [[FEATURE] - [UI] Add New Voucher - AI解析資料預覽 #2399](https://github.com/CAFECA-IO/iSunFA/issues/2399) - 5pt

共 51 點

**Comment by TzuHanLiang** [comment]
### 漏開的票補充
- [[FEATURE] - [UI] Upload certificate - 新增頁面 #2444](https://github.com/CAFECA-IO/iSunFA/issues/2444)
