### ISSUE TITLE
[FEATURE] - [UI] Add New Voucher - AI解析資料預覽

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#2399]
### Summary

在Add New Voucher選擇發票後應觸發AI解析，AI解析的資料要可以預覽

### Tasks

- AI 分析完成後，懸停按鈕會在輸入框內顯示灰色建議內容（僅在未填寫任何資料時顯示）。若用戶選擇 AI 填寫，則只會填寫空白欄位。
- 要跟設計師確認畫面 （Jodie）

**Comment by TzuHanLiang** [comment]
要實作的功能包括在「新增憑證」選擇發票後，觸發 AI 分析並顯示 AI 分析結果的預覽，具體功能如下：

### **功能列表：Add New Voucher - AI 解析資料預覽**

1. **選擇發票後觸發 AI 解析**
   - 當使用者在新增憑證的彈出視窗中選擇發票後，系統自動觸發 AI 解析，對發票內容進行分析。
   - AI 解析應在後端進行，並返回建議的欄位值和結構化資料。

2. **AI 解析進度提示**
   - 在發票選擇後觸發 AI 解析時，應顯示一個進度條或旋轉圖標，提示使用者正在進行 AI 分析。
   - 確保解析過程的時間長短對使用者有明確的反饋，避免使用者認為系統無反應。

3. **AI 解析結果顯示**
   - 分析完成後，AI 的建議內容會自動顯示在輸入欄內，作為灰色的建議文本。
   - 建議內容只會顯示在使用者尚未手動填寫的輸入框中，若使用者已經填寫，則不覆蓋現有內容。

4. **可選擇使用 AI 建議填寫**
   - 使用者可選擇接受或忽略 AI 的建議。當使用者選擇 AI 建議時，會將灰色的建議文字轉換為正式輸入內容，填入對應的輸入框中。

5. **AI 解析的資料結構**
   - AI 返回的資料應包括發票的關鍵欄位信息，例如：
     - 金額（Debit、Credit）
     - 付款對象
     - 發票號碼
     - 日期
   - 這些資料應根據後端的 AI 模型自動解析發票，並結構化顯示在前端。

6. **暫停或停止 AI 分析**
   - 在 AI 分析過程中，應提供一個暫停或取消按鈕，允許使用者手動停止 AI 解析。
   - 如果使用者暫停，輸入框應保留現有的內容，並且不再顯示 AI 的建議。

7. **API 交互功能**
   - 發送 API 請求以觸發 AI 解析，請求中應包含選中的發票 ID。
   - API 路徑：
     ```bash
     POST /api/invoices/{invoiceId}/analyze
     ```
   - API 返回的應包括發票的詳細信息和解析後的建議資料。

8. **錯誤處理**
   - 如果 AI 分析過程中出現錯誤（例如網路問題或解析失敗），應顯示錯誤訊息，並允許使用者重試解析或繼續手動輸入資料。

**Comment by Julian0701** [comment]
- take 2 hrs
- 今天只刻了畫面，還沒實作功能

**Comment by Julian0701** [comment]
- take 5 hrs, unfinished

- [ ] 選擇發票後觸發 AI 解析
- [ ] AI 解析進度提示
- [x] AI 解析結果顯示
- [x] 可選擇使用 AI 建議填寫
- [x] AI 解析的資料結構
- [ ] 暫停或停止 AI 分析
- [ ] API 交互功能
- [ ] 錯誤處理

**Comment by Julian0701** [comment]
- take 7 hrs, unfinished
- `VoucherLineBlock` 的 AI 寫入需要修理
- 需要討論停止 AI 分析、錯誤處理等

**Comment by Julian0701** [comment]
Ref:
- #3104 
- [iSunFa Voucher Meeting](https://github.com/CAFECA-IO/EventReport/issues/23)

**Comment by Julian0701** [comment]
- take 3 hrs
- 串接 Al result Mock API

**Comment by Julian0701** [comment]
- take 7 hrs, unfinished
- 已調整 askAI(POST), 剩下 getAIResult(GET)

**Comment by Julian0701** [comment]
- take 8 hrs, done
- 已完成兩支 API 的調整

**Comment by TzuHanLiang** [comment]
done by julian at 202411/28
