### ISSUE TITLE
[FEATURE] - Modify the matchmaking-related API to be consistent with other APIs

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#2629]
### Summary

修改匹配相關API，使其與其他API一致

### Tasks

修改匹配相關API，使其與其他API一致
1. 修改 mock API 
    - [x]  繼承 `IPaginatedData<T>`
    - [x]  改寫法，切分 function ，並且在每個檔案裡加上 zod 跟 interface 作為暫時回傳的依據
    - [x]  將 gig 修改為 job
2. 修改 unit test
    - [x]  測試 `handleXRequest` function就好，不用 `toHaveBeenCalledWith` 去測試整個handler
3. 修改 API 文件
    - [x]  listAllGigs改用 IPaginatedData
    - [x]  將 gig 修改為 job

### Dependencies

API Availability

**Comment by arealclimber** [comment]
修改後的 API uri
- [A030001](#createAnApplication) - `POST /job/:jobId/application` - `Create an application for a job`
- [J010001](#listAllJobs) - `GET /job` - `List all jobs`
- [J010002](#getAJobById) - `GET /job/:jobId` - `Get details of a specific job`

**Comment by arealclimber** [comment]
took 4.5 hrs
done
