### ISSUE TITLE
[FEATURE] - Remained mock api

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#2650]
### Summary

Remained mock api

### Tasks

- [X] GET dashboard pending
- [X] GET normal setting IP part
- [X] PUT setting
- [X] POST company setting
