### ISSUE TITLE
[DOCS] - Ask ai API文件

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#2687]
### Summary

Ask ai API文件

### Tasks

- [ ] Ask ai API文件

**Comment by TinyMurky** [comment]
- [ ] [askAi](https://github.com/CAFECA-IO/iSunFA/wiki/API-v2#askai)
- [ ] [askAi with resultId](https://github.com/CAFECA-IO/iSunFA/wiki/API-v2#askAi-with-resultId)
