### ISSUE TITLE
[FEATURE] - New Voucher Form 補上漏掉的欄位

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#2724]
### Summary

根據設計稿補上漏掉的欄位

### Tasks

- [x] Recurring Entry
- [x] 點擊 Save 後標示出漏填的欄位
- [ ] 根據不同的 voucher type，表單欄位和必填項目略有不同

**Comment by Julian0701** [comment]
- Receivable (日期 & 類型 & Counterparty 必填)
![image](https://github.com/user-attachments/assets/e7e4c804-f43c-4bfd-9ab1-46d6a8588dfc)

- Receivable Reverse(日期 & 類型 & Counterparty & Reverse 必填)
![image](https://github.com/user-attachments/assets/a91262c4-72cc-4458-9988-0148297ac616)

- Payable (日期 & 類型 & Counterparty 必填)
![image](https://github.com/user-attachments/assets/1e1912aa-df6c-4c28-acd9-331496a7a5b3)

- Payable Reverse(日期 & 類型 & Counterparty & Reverse 必填)
![image](https://github.com/user-attachments/assets/7150b90f-f434-4408-86b6-6f4695ca26f3)

- Asset(日期 & 類型 必填)
![image](https://github.com/user-attachments/assets/989fdf77-324c-4db8-a3c2-0263313328a6)

**Comment by Julian0701** [comment]
`reverse` 和 `asset` 欄位還在調整中，所以先不做

**Comment by Julian0701** [comment]
- take 8 hrs, done

**Comment by Julian0701** [comment]
To Do List
- [ ] 會計科目有應收付帳款時，顯示 `Counterparty`
- [ ] 會計科目有資產時，顯示`Asset`
- [ ] 應付帳款在借方 || 應收帳款在貸方，顯示`Reverse`

**Comment by Julian0701** [comment]
- take 8 hrs, unfinished
<img width="1184" alt="image" src="https://github.com/user-attachments/assets/9bf95cbe-fe60-4129-8685-78388ca80adc">

樣式須調整

**Comment by Julian0701** [comment]
- take 8 hrs, done
- 沖銷的邏輯可能還須優化，到時候另外開票處理
- 本票實際花費時間：24 hrs
