### ISSUE TITLE
[FEATURE] - Implement user action log API with test

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#2786]
### Summary

Implement user action log API

### Tasks

- [ ] store user login log in signin
- [ ] GET user/:userId/action_log
- [ ] Maybe store more log in other function

**Comment by RexBearIU** [comment]
It takes 5 hours.

done
