### ISSUE TITLE
[DOCS] - Record miss api

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#2813]
### Summary

miss api

### Tasks

- [ ] system role list

**Comment by RexBearIU** [comment]
- [ ] todo list table
- [ ] todo list api
- [ ] system role and company role

**Comment by RexBearIU** [comment]
It takes 2 hours.

contain 1 hour meeting
