### ISSUE TITLE
[FEATURE] - Modify [...next] auth for sign in and signout log

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#2919]
### Summary

Modify [...next] auth for sign in and signout log

### Tasks

- [X] add signout event
- [X] add signin and signout user log
- [X] modify frontend user context function

**Comment by RexBearIU** [comment]
It takes 3 hours.

done
