### ISSUE TITLE
[FEATURE] - Put Voucher 整體架構

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#2940]
### Summary

Put Voucher 整體架構

### Tasks

- [ ] Put Voucher 整體架構程式碼
- [ ] 需要將輔助持是在 route_util.ts
- [ ] zod 邏輯已經好了，主要架設是不是要產生反轉分錄以及儲存反轉分錄

備註：會有兩個不同邏輯：
1: 只修改非lineitems的東西 => 可直接修改
2: 修改lineItems的東西 => 需要建立沖帳

**Comment by TinyMurky** [comment]
took 3 hours
undone

**Comment by TinyMurky** [comment]
took 2 hours
done
