### ISSUE TITLE
[DOCS] - 評估 Setting 相關功能並開票

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#2998]
### Summary

評估 Setting 相關功能點數(UI / Function)

### Tasks

- [ ] **Normal Setting**:
    - User Settings
    - Notice Settings（訂閱除外）
    - Company Settings
        - Add Company
        - View all companies
        - Edit Company（增加稅務資訊）
            - [\*] Remove this company（若時間允許希望完成）
    - Account Settings
        - [\*] Remove this Account（若時間允許希望完成）
    - [!] IP Info
- [ ] **Accounting Setting**:
    - Tax Settings
    - Currency Settings
    - Accounting Settings
    - Accounting Title Settings
        - View all Accounting Title
        - Add Accounting Title
        - Remove Accounting Title
- [ ] **Client/Supplier Setting**:
    - List Client/Supplier
    - Add Client/Supplier
    - Edit Client/Supplier
    - Remove Client/Supplier

**Comment by Julian0701** [comment]
UI(39 pt)
Normal Setting (13 pt)
Normal Setting Page - 5 pt
Company Setting Modal (Company Info Modal) -  5 pt
Create New Company Modal -  1 pt
IP Info Modal - 2 pt

Accounting Setting(19 pt)
Accounting Setting Page - 5 pt
Accounting Title Setting Modal
Assets Section - 8 pt
Add New Title Section - 3 pt
Manual Account Opening Modal - 3 pt

Client/Supplier Setting(7 pt)
Client/Supplier Setting Page - 5 pt
Add/Edit New Client/Supplier - 2 pt

**Comment by Julian0701** [comment]
## Function(31 pt)
### Normal Setting (13 pt)

- Edit User Settings - 3 pt
- Edit Notice settings（訂閱除外） - 1 pt
- Add Company - 1 pt
- View all companies (search query) - 2 pt
- Edit Company（增加稅務資訊） - 2 pt
- Remove this company - 1 pt
- Remove this Account - 1 pt
- View Login device & IP List - 2 pt

### Accounting Setting(11 pt)

- Edit Tax Settings - 1 pt
- Edit Currency Settings - 1 pt
- Edit Accounting Settings  - 1 pt
- View all Accounting Title (search query) - 2 pt
- Add Accounting Title - 3 pt
- Remove Accounting Title - 1 pt
- Add Manual Account Opening - 2 pt

### Client/Supplier Setting(7 pt)

- View Client/Supplier List (search query) - 2 pt
- Add Client/Supplier - 2 pt
- Edit Client/Supplier - 2 pt
- Remove Client/Supplier - 1 pt

**Comment by Julian0701** [comment]
共 72 pt
以下根據類別分類：

------ Normal Setting (27 pt) ------
- [ ] [UI] Normal Setting Page [#3013](https://github.com/CAFECA-IO/iSunFA/issues/3013) - 5 pt
- [ ] [UI] Company Setting Modal (Company Info Modal) [#3014](https://github.com/CAFECA-IO/iSunFA/issues/3014)  -  5 pt
- [ ] [UI] Create New Company Modal [#3017](https://github.com/CAFECA-IO/iSunFA/issues/3017) -  1 pt
- [ ] [UI] IP Info Modal [#3019](https://github.com/CAFECA-IO/iSunFA/issues/3019) - 2 pt
- [ ] [Function] Edit User Settings [#3037](https://github.com/CAFECA-IO/iSunFA/issues/3037) - 3 pt
- [ ] [Function] Edit Notice settings（訂閱除外）[#3045](https://github.com/CAFECA-IO/iSunFA/issues/3045) - 1 pt
- [ ] [Function] Add Company [#3047](https://github.com/CAFECA-IO/iSunFA/issues/3047) - 1 pt
- [ ] [Function] View all companies (search query) [#3048](https://github.com/CAFECA-IO/iSunFA/issues/3048) - 2 pt
- [ ] [Function] Edit Company（增加稅務資訊）[#3049](https://github.com/CAFECA-IO/iSunFA/issues/3049) - 3 pt
- [ ] [Function] Remove this company [#3050](https://github.com/CAFECA-IO/iSunFA/issues/3050) - 1 pt (可延後處理)
- [ ] [Function] Remove this Account [#3051](https://github.com/CAFECA-IO/iSunFA/issues/3051) - 1 pt (可延後處理)
- [ ] [Function] View Login device & IP List [#3052](https://github.com/CAFECA-IO/iSunFA/issues/3052) - 2 pt

------ Accounting Setting(31 pt) ------
- [ ] [UI] Accounting Setting Page [#3021](https://github.com/CAFECA-IO/iSunFA/issues/3021) - 5 pt
- [ ] [UI] Assets Section [#3027](https://github.com/CAFECA-IO/iSunFA/issues/3027) - 8 pt
- [ ] [UI] Add New Title Section [#3030](https://github.com/CAFECA-IO/iSunFA/issues/3030) - 3 pt
- [ ] [UI] Manual Account Opening Modal [#3033](https://github.com/CAFECA-IO/iSunFA/issues/3033) - 3 pt
- [ ] [Function] Edit Tax Settings [#3053](https://github.com/CAFECA-IO/iSunFA/issues/3053) - 1 pt
- [ ] [Function] Edit Currency Settings [#3054](https://github.com/CAFECA-IO/iSunFA/issues/3054) - 1 pt
- [ ] [Function] Edit Accounting Settings [#3055](https://github.com/CAFECA-IO/iSunFA/issues/3055)  - 1 pt
- [ ] [Function] View all Accounting Title (search query) [#3056](https://github.com/CAFECA-IO/iSunFA/issues/3056) - 2 pt
- [ ] [Function] Add Accounting Title [#3057](https://github.com/CAFECA-IO/iSunFA/issues/3057) - 3 pt
- [ ] [Function] Remove Accounting Title [#3058](https://github.com/CAFECA-IO/iSunFA/issues/3058) - 1 pt
- [ ] [Function] Add Manual Account Opening #[3060](https://github.com/CAFECA-IO/iSunFA/issues/3060) - 3 pt

------ Client/Supplier Setting(14 pt)------
- [ ] [UI] Client/Supplier Setting Page [#3034](https://github.com/CAFECA-IO/iSunFA/issues/3034) - 5 pt
- [ ] [UI] Add/Edit New Client/Supplier [#3036](https://github.com/CAFECA-IO/iSunFA/issues/3036) - 2 pt
- [ ] [Function] View Client/Supplier List (search query) [#3063](https://github.com/CAFECA-IO/iSunFA/issues/3063) - 2 pt
- [ ] [Function] Add Client/Supplier [#3065](https://github.com/CAFECA-IO/iSunFA/issues/3065) - 2 pt
- [ ] [Function] Edit Client/Supplier [#3066](https://github.com/CAFECA-IO/iSunFA/issues/3066) - 2 pt
- [ ] [Function] Remove Client/Supplier [#3068](https://github.com/CAFECA-IO/iSunFA/issues/3068) - 1 pt

**Comment by Julian0701** [comment]
- take 5 hrs, done
