### ISSUE TITLE
[FEATURE] - Add stop and retry askAI with kafka

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#3031]
### Summary

Add stop and retry askAI with kafka

### Tasks

- [ ] Add stop and retry askAI with kafka
- [ ] Maybe add a stop queue?
- [ ] Maybe add a retry queue?

**Comment by RexBearIU** [comment]
Use cron job instead of kafka.
