### ISSUE TITLE
[FEATURE] - Implement list-assets API

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#3081]
### Summary

[FEATURE] - Implement list-assets API

### Tasks

[FEATURE] - Implement list-assets API

- 不回傳沒有 voucher 的 asset 
- [x] list asset repo function
- [x] list asset API
- [x] Hoppscotch
-----
- [x] 將 API query (sort, filter) 修改為 list asset repo function 可用的 param，才能透過 prisma 搜尋、排序資料
- 寫完 API 之後發現排序的 query 沒有按照 `FilterSection` component 規定的公版去寫，API 文件也沒有更新，所以先依照公版格式去寫再開票修改文件
- [x] sortOption 根據 `FilterSection` component 規定的公版去寫排序的 query 的讀取格式，但還沒有更新 API 文件 #3586
- [x] 根據修改後的 list asset repo 去修改 unit tests

```typescript
GET /company/:companyId/asset
```

![CleanShot 2024-12-09 at 17 35 28](https://github.com/user-attachments/assets/b1a3deba-a1f4-4abf-86d1-5d9b1db1d5c9)

**Comment by arealclimber** [comment]
took 1 hr
remaining 2 hrs

**Comment by arealclimber** [comment]
took 4 hrs
done
