### ISSUE TITLE
[DOCS] - DB schema modification till next sprint ~2024/11/15

### ISSUE THREAD

**Issue by RexBearIU** [CAFECA-IO/iSunFA#3159]
### Summary

DB schema modification till next sprint ~2024/11/15

### Tasks

- [ ] DB schema modification till next sprint ~2024/11/15

**Comment by RexBearIU** [comment]
companySetting {
add country code
}

**Comment by TinyMurky** [comment]
Accociate 改成 associate

**Comment by RexBearIU** [comment]
account {
add note?
}

**Comment by arealclimber** [comment]
> companySetting { add country code }

countryCode string



> Accociate 改成 associate event 裡的 frequence 改成 frequency

改欄位名字frequence=>frequency



> account { add note? }

account table 加上ｎｏｔｅ欄位

**Comment by arealclimber** [comment]
- 另外新增修改 account table 的需求 https://github.com/CAFECA-IO/iSunFA/issues/3267

**Comment by arealclimber** [comment]
1. DB Account table

   1. 改 id 的值

   2. 新增 parentId, rootId 欄位，並且依照 seed.json 去給預設會計科目的 parentId, rootId 的值

   3. 根據規則去給自訂會計科目的 parentId, rootId 的值

   4. 新增 note 選填欄位，格式為 string

   5. 移除 code 的 unique 限制

   6. 修改 parent, child 關係，改用 id 引用

2. DB CompanySetting table

   1. 新增欄位

      1. `countryCode string @default tw`

3. prisma model AccociateLineItem

   1. 改欄位名稱

      1. `accociateVoucherId` ⇒ `associateVoucherId`

      2. `accociateVoucher` ⇒ `associateVoucher`

4. prisma model AccociateVoucher

   1. 改欄位名稱

      1. associateLineItems 對應的 `AccociateLineItem` ⇒  `AssociateLineItem`

5. DB AccociateLineItem table

   1. 新增欄位

      1. countryCode string `@default tw`

6. DB Event table

   1. 改欄位名稱

      1. `frequence` ⇒ `frequency`

**Comment by arealclimber** [comment]
[updated doc](https://github.com/CAFECA-IO/Documents/tree/main/ISF)

**Comment by arealclimber** [comment]
- [x] 實作 staging db migration 

   - [x] 將 iSunFA 切到 `feature/update-migration-sql` branch

   - [x] 修改 .env 為 staging_db

   - [x] 執行以下指令

      ```bash
      # 確認連到正確的 db，比對 migrations 資料夾跟現在的 db schema
      npx prisma migrate status
      
      # 將 migrations/migration.sql 應用在 db 
      npx prisma migrate deploy
      
      # 生成 Prisma client
      npx prisma generate
      
      ```

**Comment by arealclimber** [comment]
took 2.5 hrs in total
done
