### ISSUE TITLE
[DOCS] - 清點W45~Beta Release Voucher與Certificate 剩餘點數

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#3170]
### Summary

清點W45~Beta Release Voucher與Certificate 剩餘點數

- 總共剩下141 pt
- 6pt mock
- 107pt 主要實做
- 16pt 測試
- 16pt Run time

### Tasks

> [!note]
> 重要連結
> - #3070
> - Certificate:
>> - #2984
>> - #2989
>> - #2990
>> - #2992
>> - #2994
>> - #2995
>> - #3046
>> - #3096
> - Voucher
>> - None

# Mock 缺少
- #3160 -3pt
- #3161 -3pt

###  Voucher 總共有： 82pt (其中 8pt為測試, 8pt run time, 剩下有66 pt)

> Post Voucher 14pt / 14pt 未完成
- [ ] [DOCS - Post Voucher 規劃 (ISSUE)集中區 #3171](https://github.com/CAFECA-IO/iSunFA/issues/3171) -1pt
- [ ] [[FEATURE] - (Post Voucher) Line item, Voucher Entitly Prisma Create and save #2930](https://github.com/CAFECA-IO/iSunFA/issues/2930) -3pt
- [ ] [[FEATURE] - Post Voucher Revert 邏輯實做  #2936](https://github.com/CAFECA-IO/iSunFA/issues/2936) -5pt
- [ ] [[FEATURE] - Post Voucher Asset 邏輯實做 #2937](https://github.com/CAFECA-IO/iSunFA/issues/2937) -5pt

> Put Voucher 16pt / 16pt 未完成
- [ ] [DOCS - Put Voucher 規劃 #3172](https://github.com/CAFECA-IO/iSunFA/issues/3172) -1pt
- [ ] [[FEATURE] - Put Voucher 整體架構 #2940](https://github.com/CAFECA-IO/iSunFA/issues/2940) -5pt
- [ ] [[FEATURE] - Put voucher 沒有更改line item的情況下的更新 #2941](https://github.com/CAFECA-IO/iSunFA/issues/2941) -5pt
- [ ] [[FEATURE] - Put Voucher自動產生反轉傳票 #2942](https://github.com/CAFECA-IO/iSunFA/issues/2942) -5pt

> List All Voucher  10pt / 10pt 未完成
- [ ] [[FEATURE] - List Voucher邏輯架構(不含Prisma) #2943](https://github.com/CAFECA-IO/iSunFA/issues/2943) -5pt
- [ ] [[FEATURE] - List Voucher Prisma 與 IPagination #2944](https://github.com/CAFECA-IO/iSunFA/issues/2944) -5pt

> List Voucher by account  8pt / 8pt 未完成
- [ ] [[FEATURE] - List Voucher By Account 架設整體架構 #2945](https://github.com/CAFECA-IO/iSunFA/issues/2945) -3pt
- [ ] [[FEATURE] - List Voucher by Account 計算沖帳邏輯(排除已沖帳完成的voucher)與測試 #2946](https://github.com/CAFECA-IO/iSunFA/issues/2946) -2pt
- [ ] [FEATURE - List Voucher By Account Prisma邏輯 #3173](https://github.com/CAFECA-IO/iSunFA/issues/3173) -3pt

> List line item by voucher 8pt / 8pt 未完成
- [ ] [[FEATURE] - List line item by voucher 沖帳整體架構 #2947](https://github.com/CAFECA-IO/iSunFA/issues/2947) -5pt
- [ ] [FEATURE - List line item by voucher Prisma 邏輯 #3174](https://github.com/CAFECA-IO/iSunFA/issues/3174) -3pt

> Delete Voucher  10pt / 10pt 未完成
- [ ] [[FEATURE] - Delete Voucher 架設整體邏輯 #2949](https://github.com/CAFECA-IO/iSunFA/issues/2949) -3pt
- [ ] [[FEATURE] - Delete Voucher 反轉分錄實做 #2950](https://github.com/CAFECA-IO/iSunFA/issues/2950) -5pt
- [ ] [[FEATURE] - Delete Voucher Prisma 邏輯 #3175](https://github.com/CAFECA-IO/iSunFA/issues/3175) -2pt

> test Voucher   8pt / 8pt 未完成
- [ ] [[FEATURE] - 整合測試 -Voucher 並撰寫Seeder (不含AI) #2951](https://github.com/CAFECA-IO/iSunFA/issues/2951) -8pt

> Run Time 8pt / 8pt 未完成
- [ ] [[FEATURE] - Voucher Worker, 把 Upcoming改程式Uploaded #2939](https://github.com/CAFECA-IO/iSunFA/issues/2939) -8pt

### Certificate (58pt/53pt未完成) => 53 未完成中， 8 為 runtime, 8 為測試, 剩下 37

> [!NOTE]
> Certificate 相關連結
> - [Certificate 票數規劃 & Voucher 票數重開 #2984](https://github.com/CAFECA-IO/iSunFA/issues/2984)
> - [[DOCS] - LIST Certificate 規劃 #2989](https://github.com/CAFECA-IO/iSunFA/issues/2989)
> - [[DOCS] - GET One Certificate (回IInvoiceBeta) 規劃 #2990](https://github.com/CAFECA-IO/iSunFA/issues/2990)
> - [[DOCS] - Post Certificate (Web) 規劃 #2992](https://github.com/CAFECA-IO/iSunFA/issues/2992)
> - [[DOCS] - Put Certificate規劃 #2994](https://github.com/CAFECA-IO/iSunFA/issues/2994)
> - [[DOCS] - Delete multiple certificate 規劃 #2995](https://github.com/CAFECA-IO/iSunFA/issues/2995)
> - [[DOCS] - Put Invoice 規劃 #3046](https://github.com/CAFECA-IO/iSunFA/issues/3046)
> - [FEATURE - (Certificate)手機上傳照片流程調整 #3096](https://github.com/CAFECA-IO/iSunFA/issues/3096)

> List Certificate (11pt/9pt未完成)

- [x] [[FEATURE] - List Certificate Zod接口 #3002](https://github.com/CAFECA-IO/iSunFA/issues/3002) -2pt
- [ ] [[FEATURE] - List Certificate API主體邏輯 #3003](https://github.com/CAFECA-IO/iSunFA/issues/3003) -3pt
- [ ] [[FEATURE] - List Certificate prisma 實做 #3004](https://github.com/CAFECA-IO/iSunFA/issues/3004) -3pt
- [ ] [[FEATURE] - Certificate Seeder #3005](https://github.com/CAFECA-IO/iSunFA/issues/3005) -1pt
- [ ] [[FEATURE] - List Certificate integration test #3006](https://github.com/CAFECA-IO/iSunFA/issues/3006) -2pt

> Get Certificate (8pt/6pt未完成)

- [x] [[FEATURE] - Get one Certificate Zod設計 #3007](https://github.com/CAFECA-IO/iSunFA/issues/3007) -2pt
- [ ] [[FEATURE] - Get Certificate index邏輯 #3008](https://github.com/CAFECA-IO/iSunFA/issues/3008) -2pt
- [ ] [[FEATURE] - Get One Certificate prisma邏輯 #3009](https://github.com/CAFECA-IO/iSunFA/issues/3009) -2pt
- [ ] [[FEATURE] - Get one Voucher integration test #3011](https://github.com/CAFECA-IO/iSunFA/issues/3011) -2pt

> Post Certificate (11pt/10pt未完成)

- [ ] [[FEATURE] - Post Certificate 成功時串接Pusher #3010](https://github.com/CAFECA-IO/iSunFA/issues/3010) -1pt
- [x] [[FEATURE] - Post Certificate Zod設計 #3012](https://github.com/CAFECA-IO/iSunFA/issues/3012) -1pt
- [ ] [[FEATURE] - Post Certificate api實做架構 #3022](https://github.com/CAFECA-IO/iSunFA/issues/3022) -3pt
- [ ] [[FEATURE] - Post Certificate Prisma邏輯 #3028](https://github.com/CAFECA-IO/iSunFA/issues/3028) -1pt
- [ ] [[FEATURE] - Post Certificate integration test #3024](https://github.com/CAFECA-IO/iSunFA/issues/3024) -5pt

> Delete Certificate Multiple (6pt/6pt未完成)

- [ ] [[FEATURE] - Delete multiple Certificate zod 設計 #3039](https://github.com/CAFECA-IO/iSunFA/issues/3039) -1pt
- [ ] [[FEATURE] - Delete multiple certificate api 架構實做 #3040](https://github.com/CAFECA-IO/iSunFA/issues/3040) -1pt
- [ ] [[FEATURE] - Delete multiple certificate Prisma logic #3041](https://github.com/CAFECA-IO/iSunFA/issues/3041) -2pt
- [ ] [[FEATURE] - Delete multiple certificate integration test #3042](https://github.com/CAFECA-IO/iSunFA/issues/3042) -2pt

> Certificate 手機相關 (9pt/9pt未完成)
- [ ] [[DOCS] - 改寫 /Pusher 規劃 #2999](https://github.com/CAFECA-IO/iSunFA/issues/2999) -3pt
- [ ] [[DOCS] - 改寫 /encrypt 規劃 #3000](https://github.com/CAFECA-IO/iSunFA/issues/3000) -3pt
- [ ] [[DOCS] - 改寫手機板Upload圖片的 /upload規劃 #3001](https://github.com/CAFECA-IO/iSunFA/issues/3001) -3pt

> Put Invoice (5pt/5pt未完成)

- [ ] [[FEATURE] - Put invoice zod 規劃 #3059](https://github.com/CAFECA-IO/iSunFA/issues/3059) -1pt
- [ ] [[FEATURE] - put invoice 整體架構 #3061](https://github.com/CAFECA-IO/iSunFA/issues/3061) -1pt
- [ ] [[FEATURE] - put invoice prisma #3062](https://github.com/CAFECA-IO/iSunFA/issues/3062) -1pt
- [ ] [[FEATURE] - Put invoice integration test #3064](https://github.com/CAFECA-IO/iSunFA/issues/3064) -2pt

> Runtime (8pt/8pt未完成)
- [ ] [[FEATURE] - Certificate Worker for pusher and Message Queue #3020](https://github.com/CAFECA-IO/iSunFA/issues/3020) -8pt
