### ISSUE TITLE
[FEATURE] - Refactor the export-file to export-asset API

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#3181]
### Summary

[功能] - 將匯出檔案重構為匯出資產 API（並非一體化）

### Tasks

- [x] 將 export-file 改為 export-asset API
- [x] 在 export-asset 加上 validate authorization, input, output ; format output 邏輯跟 logUserAction 
=> 引用 middleware 裡的 function ，直接抄 withRequestValidation 的寫法會在沒登入的時候等不到 response，花時間排查之後改寫為 try-catch
- [x] 加上 TODO，之後回來重構 middleware 適應 API 直接回傳檔案的情境

**Comment by arealclimber** [comment]
https://github.com/user-attachments/assets/a97ffb64-616c-431f-994c-450857289c7a

**Comment by arealclimber** [comment]
took 3 hrs
done
