### ISSUE TITLE
[DOCS] - Plan the tasks to execute the conclusion of meeting

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#3257]
### Summary

- 根據 11/18 會議規劃執行內容

ref
- [會議資訊](https://github.com/CAFECA-IO/EventReport/blob/main/meeting/20241114_isunfa_backend_algorithm.md)
- [會議連結](https://meet.google.com/zdu-fnmx-bda)
- [參考程式碼](https://github.com/CAFECA-IO/iSunFA/blob/feature/account_book/src/lib/utils/account/account_book.ts)

### Tasks

- 會議結論：透過統一的 class （account book node class and account book class）去實作會計系統的外帳功能，包含報表、會計科目試算表、分類帳，實作 code [參考程式碼](https://github.com/CAFECA-IO/iSunFA/blob/feature/account_book/src/lib/utils/account/account_book.ts)
- ~[demo code](https://github.com/CAFECA-IO/iSunFA/blob/feature/account_book/src/lib/utils/account/account_book.ts) 沒列到分類帳的實作 code，但一樣算在此次執行範圍內~
- 此張票的目的是根據會議內容跟分配到的工作內容，去規劃重構試算表（trial balacne）跟分類帳（ledger）要做的事情
-----
- [ ] CAFECA-IO/EventReport#42
- [ ] CAFECA-IO/iSunFA#3263
- [ ] CAFECA-IO/iSunFA#3264

**Comment by arealclimber** [comment]
took 1 hr
done
