### ISSUE TITLE
Fix: create todo modal and connect  list company api (simple version)

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#3282]
- [x] 確認表單第三個欄位是要放入什麼？
- [x] fix connecting create todo api
- [x] connect list company api (simple version)
- [x] 修改 date picker 有缺少 key 的警告訊息
- [ ] #3297

**Comment by godmmt** [comment]
### 修改 date picker 讓日期可以選擇未來的日期

![截圖 2024-11-19 23 11 58](https://github.com/user-attachments/assets/5222e001-09ca-40d6-878b-5f969a86312b)

**Comment by godmmt** [comment]
### 確認表單第三個欄位是要放入什麼？

![截圖 2024-11-19 23 11 47](https://github.com/user-attachments/assets/1a0143c9-41f7-40d7-9630-2fb37beb5fd6)

第三個欄位似乎不是「夥伴類型」

打 API 的錯誤訊息顯示似乎是要傳 `companyId`

**Comment by godmmt** [comment]
### 確認結果第三個欄位是 Affiliated Company

下拉選單的選項是使用者所有擁有的公司

### API

1. 建立 todo API : 
    
    CREATE_TODO = ${apiPrefixV2}/user/:userId/todo
    
    const { companyId, name, note, deadline } = body;

2. 下拉選單要打 list user company API

    @RexBearIU 會再提供一個簡單版本的 API , 會回傳 `ICompany[]`

**Comment by godmmt** [comment]
延伸: https://github.com/CAFECA-IO/iSunFA/issues/3291

**Comment by godmmt** [comment]
修改 date picker 讓日期可以選擇未來的日期 
這部分是新增新功能，需要花比較多時間，所以另外開單 👉 #3297

**Comment by godmmt** [comment]
# 修改 date picker 有缺少 key 的警告訊息

<img width="1920" alt="截圖 2024-11-20 17 46 12" src="https://github.com/user-attachments/assets/833a3dc0-9fb7-4d5d-9642-cea0ca517471">

原本的 key 用 `el?.date` 去控制
但這樣會有幾個日期的 key 是 undefined
因此引發 React 警告

現在改成這樣去製造 key 給那些沒有 el.date 的日期 : 

```
key={el?.date || `${Date.now()}-${index}`}
```

**Comment by godmmt** [comment]
took 5 hours

done

**Comment by godmmt** [comment]
# 發現打建立 todo api 還是失敗

原因是因為公司是必填

但設計稿不是必填

所以要請後端再改

**Comment by godmmt** [comment]
took 6 hours

done

**Comment by godmmt** [comment]
took 6.5 hours

done

**Comment by godmmt** [comment]
> # 發現打建立 todo api 還是失敗
> 原因是因為公司是必填
> 
> 但設計稿不是必填
> 
> 所以要請後端再改

今天後端已經修
建立成功後回傳的 todo 的 company list 中如果是沒有填公司的 todo 會是 company id `555`
