### ISSUE TITLE
[FEATURE] - 調整 Create Asset 流程

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/iSunFA#3454]
### Summary

調整 Asset 相關流程

### Tasks

- [meeting report](https://github.com/CAFECA-IO/EventReport/blob/main/meeting/20241205_isunfa_create_assets.md)
- [x] 新增 Asset 的數量為 1 時用原本的 API [createAsset](https://github.com/CAFECA-IO/iSunFA/wiki/API-v2#createasset)，數量大於 1 時用另一支 [createManyAsset](https://github.com/CAFECA-IO/iSunFA/wiki/API-v2#createassetbulk)
- [x] createManyAsset 會回傳 `Array<CREATE_ASSET_PAYLOAD>` 格式內容，需要存入 `temporaryAssetList`
- [x] 編輯 asset 時，資產類型、資產編號、數量不可修改
- [x] Add asset modal 有錯誤需要修理
- [x] Asset No 的 Placeholder 範例須調整
- [x] 沒有和傳票綁定的待刪除資產，其頁面應該導向 404 ，避免被使用者看見

**Comment by Julian0701** [comment]
- take 8 hrs, done
- 顯示有錯誤，須另開票處理
<img width="787" alt="image" src="https://github.com/user-attachments/assets/b14a9b35-026b-43b6-85ff-8594f87fb907">
