### ISSUE TITLE
[FEATURE] - DB migration demands aside from sprint 2024/12/13

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#3674]
### Summary

[FEATURE] - 帳戶表的資料庫遷移需求

### Tasks

# 需修改的 table
- ✅account table: 根據 [ER](https://github.com/CAFECA-IO/EventReport/issues/30) 得知父科目不會在開傳票出現，但是會在 ledger & trial balance 出現，故需在 account table 把欄位 forUser 改成 forUserVoucher，然後新增欄位 forUserLedger ，去區分開傳票時不能顯示但是在 ledger 跟 trial balance 可以顯示的會計科目
- ✅country table: 新增 phone_example, code 欄位 ([ref](https://github.com/CAFECA-IO/iSunFA/issues/3666#issuecomment-2548079830))
- ✅asset table: 把 residualValue 欄位加回來

# 實驗跟處理步驟
- 流程參考 #3649 
- [x] 更改 schema 
- [x] 更改 migration.sql
- [x] 更改 seed

**Comment by arealclimber** [comment]
took 0.5 hrs
remaining 4.5 hrs

**Comment by arealclimber** [comment]
# asset

- [x] 把 residualValue 欄位加回來

   - [x] 從 migration.sql 裡移除 `DROP COLUMN “residual_value“`

   - [x] 把 schema.prisma 裡的 residualValue 加回來



# country 

- [x] schema 新增 phone_example, code 欄位

- [x] 新資料庫的資料透過 seed 新增欄位

- [x] 現有資料庫裡的現有資料透過 migration.sql 補上欄位資料



# account

1. `forUserVoucher`

2. `forUserLedger`

- [x] 新增欄位 forUserLedger

- [x] 把 forUser rename 成 `forUserVoucher`

- [x] 先複製`forUserVoucher`的值貼上給`forUserLedger` 之後，將`forUserLedger`設為 required

- [x] 將`forUserVoucher`的值的父科目改為 false；也就是預設會計科目都設為 false

**Comment by arealclimber** [comment]
took 5 hrs
done
