### ISSUE TITLE
[Fix] ToDoListPage & Dashboard TodayTodoList - get todo api

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#3678]
# 測試並且調整相關 api
- [x] 事件列表 get todo api
- [x] 儀表板 get todo api

# 確認 UI 畫面是否正確顯示
- [x] 事件列表 ToDoListPage
- [x] 儀表板 Dashboard TodayTodoList

**Comment by godmmt** [comment]
# 事件列表

- [ ] List 要拿取 `endTime`

<img width="1280" alt="截圖 2024-12-18 下午5 02 22" src="https://github.com/user-attachments/assets/c3c7f02a-a42d-4b81-a63e-73aee44fb8b0" />

**Comment by godmmt** [comment]
<img width="1280" alt="截圖 2024-12-18 下午5 52 58" src="https://github.com/user-attachments/assets/65962c9e-8e9f-4dc9-83be-a39ab75a1545" />

**Comment by godmmt** [comment]
Dashboard TodayTodoList UI 要調整的部分比預期多

**Comment by godmmt** [comment]
https://github.com/user-attachments/assets/0d66fefe-c12a-42be-9145-b8f65d41c7b8

**Comment by godmmt** [comment]
- 1218 : took 1 
- 1219 : took 2 

Total time: 3 hours

done
