### ISSUE TITLE
[FEATURE] - Refactor ledger API

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#3721]
### Summary

[功能] - 重構[list ledger API](https://github.com/CAFECA-IO/iSunFA/wiki/API-v2#listledger)

- ref
    - https://github.com/CAFECA-IO/EventReport/issues/56
    - https://github.com/CAFECA-IO/EventReport/issues/55

```
GET /company/:companyId/ledger
```

### Tasks

- [x] 區分 repo function 以及非 repo function；操作 db 需調用 repo function，而 repo function 定義在 `x.repo.ts` file
- [x] 只有 db table 才有對應的 `x.repo.ts` file
- [x] 將主邏輯寫在 API file
- [x] 父科目不需加總子科目
- [x] 同一科目需要累加 balance
- ~損益表科目的 begin credit/debit amount 為 0 ，不需加總以前的 line item~
- [x] 使用 companyId `10000007 `, startDate `1704038400`, endDate `1734796799` 驗算總借貸平衡數字為 `1313296 `

```
http://localhost:3000/api/v2/company/10000007/ledger?startDate=1704038400&endDate=1734796799&startAccountNo=&endAccountNo=&labelType=all&pageSize=99999
```

**Comment by arealclimber** [comment]
took 1 hr
remaining 4 hrs

**Comment by arealclimber** [comment]
took 4.5 hrs
done
