### ISSUE TITLE
[FEATURE] - certificate 及 voucher UI 調整並修復全選以及發票在傳票中選擇的問題

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/iSunFA#3815]
### Summary

certificate 及 voucher UI 調整並修復全選以及發票在傳票中選擇的問題

### Tasks

- [x] certificate table 補上全選功能
<img width="1148" alt="截圖 2024-12-26 下午12 12 03" src="https://github.com/user-attachments/assets/0d936959-8bb1-48c8-8985-a5d660501144" />
全選的功能不能用

- [x] 稅務資料沒有填寫改成 '-'
- [x] 補上上傳者的頭像
<img width="1148" alt="截圖 2024-12-26 下午12 22 42" src="https://github.com/user-attachments/assets/d40d119c-61eb-41cc-b2af-f6fee5679e39" />

- 稅務資料未登打的情況下，稅別應該是沒有資料的，幫我顯示"-"
- 大頭貼顯示錯誤(非真的使用者的大頭貼)

- [x] 移除稅務資料編輯登打頁面選擇發票種類中的「全部」的選項

<img width="240" alt="截圖 2024-12-26 下午12 35 58" src="https://github.com/user-attachments/assets/285c595f-0155-43b4-8c70-bab88dbc86b2" />

在稅務資料登打頁面選擇發票種類時，不應該有「全部」，的選項

- [x] fix 傳票清單上的 tap
<img width="1114" alt="截圖 2024-12-26 下午2 00 00" src="https://github.com/user-attachments/assets/96f1c7e4-f612-499d-a500-4a0e7c58c153" />

在傳票清單若選取上方兩個Tap，則無法正常顯示傳票。
預設應是一進來就在已過帳傳票頁面

- [x] 傳票編號改為 link
<img width="1143" alt="截圖 2024-12-26 下午4 00 17" src="https://github.com/user-attachments/assets/dba45899-9f94-4888-a7ee-8cd90dacbe3e" />

**此處應翻譯成傳票編號，且下方藍色編號為Link，可以連結到該傳票詳細頁面**

### Dependencies

Frontend Framework

**Comment by TzuHanLiang** [comment]
https://github.com/user-attachments/assets/7f4d2920-95b9-48de-9b60-4165b14b0573

<img width="1673" alt="Screenshot 2024-12-27 at 5 18 54 PM" src="https://github.com/user-attachments/assets/b453d852-9b67-4ad5-8176-c4865f7c5b10" />

https://github.com/user-attachments/assets/229d7ddc-0ba9-455c-be20-778472d98ab8

https://github.com/user-attachments/assets/8c33cd3f-10e5-4e50-b579-1c2d1c37ef4a


https://github.com/user-attachments/assets/b93f7ddc-f8bf-46bb-9aac-6d29fc7adee4

took 5hrs
done
