### ISSUE TITLE
check Login / Accounting / Dashboard if there are any missing components

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunFA#592]
check Login / Accounting / Dashboard if there are any missing components

- [x] #620
- [x] #621
- [x] #622

And update them in original issues:

- #481 
- #488 
- #483 

---

Login Mockup : See https://github.com/CAFECA-IO/iSunFA/issues/592#issuecomment-2102209821

Accounting Mockup step by step : See https://github.com/CAFECA-IO/iSunFA/issues/488#issuecomment-2102395672

---

New

- [x] Todo:https://github.com/CAFECA-IO/iSunFA/issues/592#issuecomment-2102343553

**Comment by godmmt** [comment]
# Login

![image](https://github.com/CAFECA-IO/iSunFA/assets/105651918/0558d6ae-cbac-46ca-8d59-4d4b22c07a87)

![image](https://github.com/CAFECA-IO/iSunFA/assets/105651918/6af2c8c4-0bcf-4f73-95ad-542d0beab7d3)

# Check

- [ ] ISFMK00001 - Login Page
- [ ] Modal_Base - Set User Name
- [ ] Modal_Base - Passkey support summary
- [ ] ISFMK00004 - Login Page-Select company
- [ ] Toast - Success - Congratulations! You've successfully joined the ISUNONE team!
- [ ] Modal - Add company to list
- [ ] Modal - Create My Entity
- [ ] Modal - Duplicate registration

**Comment by godmmt** [comment]
# GlobalContext import these components (for now):

- [ ] PasskeySupportModal
- [ ] RegisterFormModal
- [ ] AddBookmarkModal
- [ ] MessageModal
- [ ] ConfirmModal
- [ ] AddAssetModal
- [ ] CameraScanner
- [ ] PreviewInvoiceModal
- [ ] EmbedCodeModal

**Comment by godmmt** [comment]
# Login Check

- [x] ISFMK00001 - Login Page
- [x] Modal_Base - Set User Name → RegisterFormModal
- [x] Modal_Base - Passkey support summary → PasskeySupportModal
- [ ] ISFMK00004 - Login Page-Select company
- [ ] Toast - Success - Congratulations! You've successfully joined the ISUNONE team!
- [ ] Modal - Add company to list
- [ ] Modal - Create My Entity
- [ ] Modal - Duplicate registration

**Comment by godmmt** [comment]
# GlobalContext import these components (for now):

- [x] PasskeySupportModal
- [x] RegisterFormModal
- [ ] AddBookmarkModal
- [ ] MessageModal
- [ ] ConfirmModal
- [ ] AddAssetModal
- [ ] CameraScanner
- [ ] PreviewInvoiceModal
- [ ] EmbedCodeModal

**Comment by godmmt** [comment]
took 1 hour

remain 2

**Comment by godmmt** [comment]
# Login Update

![iSunFA-CP-Login](https://github.com/CAFECA-IO/iSunFA/assets/105651918/53183e36-e0ab-47b9-94fa-9d5c926c0cd6)

**Comment by godmmt** [comment]
took 1.5 hour

remain 1.5

**Comment by godmmt** [comment]
# Todo:

- [ ] Add Toast component to Component Diagram (Ref:  #580)
- [ ] so maybe `SuccessJoinToast` will be deleted (?)

**Comment by godmmt** [comment]
Accounting Mockup step by step : See https://github.com/CAFECA-IO/iSunFA/issues/488#issuecomment-2102395672

**Comment by godmmt** [comment]
# Login Update

![iSunFA-CP-Login](https://github.com/CAFECA-IO/iSunFA/assets/105651918/dfcf7880-742f-4641-ac54-346b8d70b41e)

**Comment by godmmt** [comment]
- [ ] import PasskeySupportModal from '../components/passkey_support_modal/passkey_support_modal';
- [ ] import RegisterFormModal from '../components/register_form_modal/register_form_modal';
- [ ] import AddBookmarkModal from '../components/add_bookmark_modal/add_bookmark_modal';
- [ ] import MessageModal from '../components/message_modal/message_modal';
- [ ] import ConfirmModal from '../components/confirm_modal/confirm_modal';
- [ ] import AddAssetModal from '../components/add_asset_modal/add_asset_modal';
- [ ] import CameraScanner from '@/components/camera_scanner/camera_scanner';
- [ ] import PreviewInvoiceModal from '@/components/preview_invoice_modal/preview_invoice_modal';
- [ ] import EmbedCodeModal from '../components/embed_code_modal/embed_code_modal';

**Comment by godmmt** [comment]
# Accounting Update

![iSunFA-CP-Accounting](https://github.com/CAFECA-IO/iSunFA/assets/105651918/ee101de8-572e-454f-b53e-1e6fb422c088)

**Comment by godmmt** [comment]
took 4.5 hours

remain 2

**Comment by godmmt** [comment]
太亂了 決定拆 issue

**Comment by godmmt** [comment]
took 1 hour planning

done.
