### ISSUE TITLE
[Plan] company development

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#595]
規劃開發 company 的 UI 跟 API 的任務
- [參考用的白板](https://app.heptabase.com/w/2bc389441bf4794e08d64cf88dd29168e018560766feb4ee1d20a1af18fbbf58)｜https://github.com/CAFECA-IO/iSunFA/issues/595#issuecomment-2103851224 
- ref: [mockup](https://www.figma.com/design/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?node-id=1254-210537&m=dev)｜[API - v1.0.0 doc](https://github.com/CAFECA-IO/iSunFA/wiki/API-v1.0.0)
-----
- [ ] #606
- [ ] #607
- [ ] #608
- [ ] #609
- [ ] #610
- [ ] #611
- [ ] #612
- [ ] #613
- [ ] #614
- [ ] #615
- [ ] #617
- [ ] #618
-----
### ref

- page:\
   <https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?type=design&node-id=1254%3A210537&mode=design&t=zy2VvUqXe872G6wH-1>

- module:\
   <https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?type=design&node-id=31%3A29895&mode=design&t=zy2VvUqXe872G6wH-1>

**Comment by arealclimber** [comment]
[白板](https://app.heptabase.com/w/2bc389441bf4794e08d64cf88dd29168e018560766feb4ee1d20a1af18fbbf58)

- iSunFA 流程

   - 「登入 -> 選擇公司 -> 掃描收據 -> 建立日記帳 -> 建立傳票 -> Dashboard 開始有圖表資料 -> 建立會計報表 -> 建立審計報告」

### 任務描述

- 主要內容

   - UI

      - 新增公司 mobile / desktop

         - 6 hrs

      - 選擇公司 mobile / desktop

         - 6 hrs

   - 串接 API 8 hrs

      - 新增公司 

      - 選擇公司 



### ref

- page:\
   <https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?type=design&node-id=1254%3A210537&mode=design&t=zy2VvUqXe872G6wH-1>

- module:\
   <https://www.figma.com/file/gE08fl0d4uDLvxO0HJ1xuU/iSunFA-Mockup?type=design&node-id=31%3A29895&mode=design&t=zy2VvUqXe872G6wH-1>

**Comment by arealclimber** [comment]
- iSunFA 流程
    - 「登入 -> 選擇公司 -> 掃描收據 -> 建立日記帳 -> 建立傳票 -> Dashboard 開始有圖表資料 -> 建立會計報表 -> 建立審計報告」

### 任務描述

- 主要內容
    - UI (mobile / desktop) 
        - [ ]  📝 `Toast (successful)`
        - [ ]  📝 `MessageModal (duplicate registration & entity already exist)`
        - [ ]  📝 Add functionality of switching entity in NavBar
        - [ ]  📝 Select-company page
        - 新增公司 
            - [ ]  📝 `CreateEntityModal`
        - 選擇公司 
            - [ ]  📝 Menu to select an entity on select-company page
        - 加入公司 
            - [ ]  📝 `EntityInvitationModal`
    - 串接 API 
        - [ ]  📝 新增公司 串接API
        - [ ]  📝 選擇公司 串接API
        - [ ]  📝 加入公司 串接API

**Comment by arealclimber** [comment]
## Company - frontend development 完成: 0 pt 剩餘: 41 pt
- [ ] [📝 `Toast (successful)` RWD #606](https://github.com/CAFECA-IO/iSunFA/issues/606)  - 5 pt
- [ ] [📝 `MessageModal (duplicate registration & entity already exist)` RWD #607](https://github.com/CAFECA-IO/iSunFA/issues/607)  - 5 pt
- [ ] [📝 Add functionality of switching entity in NavBar (mobile & desktop) #608](https://github.com/CAFECA-IO/iSunFA/issues/608)  - 2 pt
- [ ] [📝 Select-entity page (mobile & desktop) #609](https://github.com/CAFECA-IO/iSunFA/issues/609)  - 5 pt
- [ ] [📝 `CreateEntityModal` (mobile & desktop) #610](https://github.com/CAFECA-IO/iSunFA/issues/610)  - 8 pt
- [ ] [📝 Menu to select an entity on select-company page (mobile & desktop) #611](https://github.com/CAFECA-IO/iSunFA/issues/611)  - 5 pt
- [ ] [📝 `EntityInvitationModal` (mobile & desktop) #612](https://github.com/CAFECA-IO/iSunFA/issues/612)  - 5 pt
- [ ] [📝 新增公司 串接API #613](https://github.com/CAFECA-IO/iSunFA/issues/613)  - 2 pt
- [ ] [📝 選擇公司 串接API #614](https://github.com/CAFECA-IO/iSunFA/issues/614)  - 2 pt
- [ ] [📝 加入公司 串接API #615](https://github.com/CAFECA-IO/iSunFA/issues/615)  - 2 pt

**Comment by arealclimber** [comment]
## Company - frontend development 41 pt
- [ ] [📝 `Toast (successful)` RWD #606](https://github.com/CAFECA-IO/iSunFA/issues/606)  - 5 pt
- [ ] [📝 `MessageModal (duplicate registration & entity already exist)` RWD #607](https://github.com/CAFECA-IO/iSunFA/issues/607)  - 5 pt
- [ ] [📝 Add functionality of switching entity in NavBar (mobile & desktop) #608](https://github.com/CAFECA-IO/iSunFA/issues/608)  - 2 pt
- [ ] [📝 Select-entity page (mobile & desktop) #609](https://github.com/CAFECA-IO/iSunFA/issues/609)  - 5 pt
- [ ] [📝 `CreateEntityModal` (mobile & desktop) #610](https://github.com/CAFECA-IO/iSunFA/issues/610)  - 8 pt
- [ ] [📝 Menu to select an entity on select-company page (mobile & desktop) #611](https://github.com/CAFECA-IO/iSunFA/issues/611)  - 5 pt
- [ ] [📝 `EntityInvitationModal` (mobile & desktop) #612](https://github.com/CAFECA-IO/iSunFA/issues/612)  - 5 pt
- [ ] [📝 新增公司 串接API #613](https://github.com/CAFECA-IO/iSunFA/issues/613)  - 2 pt
- [ ] [📝 選擇公司 串接API #614](https://github.com/CAFECA-IO/iSunFA/issues/614)  - 2 pt
- [ ] [📝 加入公司 串接API #615](https://github.com/CAFECA-IO/iSunFA/issues/615)  - 2 pt

**Comment by arealclimber** [comment]
## Company - frontend development 49 pt
- [ ] [📝 `Toast (successful)` RWD #606](https://github.com/CAFECA-IO/iSunFA/issues/606)  - 5 pt
- [ ] [📝 `MessageModal (duplicate registration & entity already exist)` RWD #607](https://github.com/CAFECA-IO/iSunFA/issues/607)  - 5 pt
- [ ] [📝 Add functionality of switching entity in NavBar (mobile & desktop) #608](https://github.com/CAFECA-IO/iSunFA/issues/608)  - 2 pt
- [ ] [📝 Select-entity page (mobile & desktop) #609](https://github.com/CAFECA-IO/iSunFA/issues/609)  - 5 pt
- [ ] [📝 `CreateEntityModal` (mobile & desktop) #610](https://github.com/CAFECA-IO/iSunFA/issues/610)  - 8 pt
- [ ] [📝 Menu to select an entity on select-company page (mobile & desktop) #611](https://github.com/CAFECA-IO/iSunFA/issues/611)  - 5 pt
- [ ] [📝 `EntityInvitationModal` (mobile & desktop) #612](https://github.com/CAFECA-IO/iSunFA/issues/612)  - 5 pt
- [ ] [📝 新增公司 串接API #613](https://github.com/CAFECA-IO/iSunFA/issues/613)  - 2 pt
- [ ] [📝 選擇公司 串接API #614](https://github.com/CAFECA-IO/iSunFA/issues/614)  - 2 pt
- [ ] [📝 加入公司 串接API #615](https://github.com/CAFECA-IO/iSunFA/issues/615)  - 2 pt
- [ ] [Without subscription, the consistent banner of trial on all users pages #617](https://github.com/CAFECA-IO/iSunFA/issues/617)  - 5 pt
- [ ] [company data in context #618](https://github.com/CAFECA-IO/iSunFA/issues/618)  - 3 pt

**Comment by arealclimber** [comment]
taking 2 hrs
