### ISSUE TITLE
[Main Task] Murky 要做的alpha 東西集中區

### ISSUE THREAD

**Issue by TinyMurky** [CAFECA-IO/iSunFA#91]
# 已完成 (0 pt) / 規劃 (0 pt)

# Research
- [x] CAFECA-IO/iSunFA#92
    - [x] CAFECA-IO/iSunFA#126
    - [x] CAFECA-IO/iSunFA#136
- [x] CAFECA-IO/iSunFA#93
    - [x] CAFECA-IO/iSunFA#140
    - [x] CAFECA-IO/iSunFA#141
    - [x] #332
- [x] CAFECA-IO/iSunFA#143
# 開會
- [x] CAFECA-IO/BAIFA#1053
- [x] #152 
- [x] #153  
- [x] #165 
- [x] #1589

# Mock
- [x] #166
    - [x] #259 
    - [x] #260 
- [x] #167
- [x] #168
- [x] #179
- [x] #169
- [x] #170
- [x] #180
- [x] Google vision
    - [x] #270
    - [x] #271
- [x] #451
- [x] #452
- [x] #453
- [x] #454
- [x] #561
- [x] #586 
- [x] #587 
- [x] #588 
- [x] #589
- [x] #590
- [x] #1052

# Test
- [x] #171 
- [x] #172 
- [x] #256
- [x] #390
- [x] #391
- [x] #392
- [x] #861
- [x] #893
- [x] #986
- [x] #987
- [x] #1011

# Document
- [x] #173
- [x] #174
- [x] #175
- [x] #1066
- [x] #1068
- [x] #1070
- [x] #1071

# research
- [x] #805

# Coding
- [x] #328
- [x] #351
- [x] #350
- [x] #359
- [x] #360
- [x] #506
- [x] #507
- [x] #529
- [x] #538
- [x] #545
- [x] #563
    - [x] #564
    - [x] #565
    - [x] #566
- [x] #569
- [ ] #659
- [x] #665
- [x] #664
- [x] #687
- [x] #715
- [x] #716
- [x] #718
- [x] #1007
- [x] #1008
- [x] #1029
- [x] #1097
- [x] #1162
- [x] #1163
- [ ] #1173
- [ ] #1174
- [x] #1279
    - [x] #1284 
    - [x] #1285 
    - [x] #1286 
    - [x] #1287 
    - [x] #1288 
    - [x] #1289 
    - [x] #1324 
- [x] #1329
    - [x] #1330 
    - [x] #1331
    - [x] #1360 
    - [x] #1361 
    - [x] #1362 
    - [x] #1363 
    - [x] #1388 
- [x] #1337
    - [x] #1339
        - [x] #1340 
        - [x] #1341  
    - [x] #1342
        - [x] #1343 
        - [x] #1344 
    - [x] #1345
        - [x] #1346 
        - [x] #1347  
    - [x] #1349
    - [x] #1352
    - [x] #1354
    - [x] #1355
    - [x] #1356
- [x] #1470 
- [x] #1472 
- [x] #1473 
- [x] #1474
- [x] #1475 
- [x] #1476 
- [x] #1477
- [x] #1533
- [x] #1588

# Journal 相關的東西
- [x] #722 
- [x] #724 
- [x] #725 
- [x] #726 
- [x] #727
- [x] #728
- [x] #729
- [x] #730
- [x] #771
- [x] #772
- [x] #773
- [x] #774
- [x] #775
- [x] #827
- [x] #828
- [x] #776
- [x] #777
- [x] #779
- [x] #917
- [x] #944
- [x] #951
- [ ] #999
- [x] #1018
- [x] #1518 
- [x] #1519 
- [x] #1520 
- [x] #1521 
- [x] #1522 

# 其他
- [x] #843
- [x] #928
- [x] #930
- [x] #936
- [x] #937
- [x] #1045
- [x] #1208
- [x] #1216
- [x] #1281
- [x] #1314
- [x] #1531 

# Report Generate
- [x] #1221
- [x] #1260
# Bug
- [x] #943
- [x] #964
- [x] #1306
- [x] #1332

# Bug
- [ ]  #1403
- [x] #1532

**Comment by TinyMurky** [comment]
alpha版本完成
