### ISSUE TITLE
[Plan] internationlization JSON doc of existing developed pages

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/iSunFA#952]
查看現有已開發的網頁，開票紀錄對應的 i18n 文檔，但實際處理者不一定是我， assignee 可先空著
- [ ] #106
- [ ] #1030
- [ ] #1031
- [ ] #1032
- [ ] #1033
- [ ] #1034
- [ ] #1035
- [ ] #1036
- [ ] #1038

**Comment by arealclimber** [comment]
# 預計需要 17 pt

- [ ] [Login internationalization json doc #106](https://github.com/CAFECA-IO/iSunFA/issues/106)  - 3 pt
- [ ] [i18n JSON - general components #1030](https://github.com/CAFECA-IO/iSunFA/issues/1030)  - 3 pt
- [ ] [i18n JSON - select-company page #1031](https://github.com/CAFECA-IO/iSunFA/issues/1031)  - 1 pt
- [ ] [i18n JSON - dashboard page #1032](https://github.com/CAFECA-IO/iSunFA/issues/1032)  - 2 pt
- [ ] [i18n JSON - project page #1033](https://github.com/CAFECA-IO/iSunFA/issues/1033)  - 2 pt
- [ ] [i18n JSON - account page #1034](https://github.com/CAFECA-IO/iSunFA/issues/1034)  - 2 pt
- [ ] [i18n JSON - salary page #1035](https://github.com/CAFECA-IO/iSunFA/issues/1035)  - 1 pt
- [ ] [i18n JSON - report page #1036](https://github.com/CAFECA-IO/iSunFA/issues/1036)  - 2 pt
- [ ] [i18n JSON - Audit report page #1038](https://github.com/CAFECA-IO/iSunFA/issues/1038)  - 1 pt

**Comment by arealclimber** [comment]
took 2 hrs
done
